// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GpsNavigator.proto

package com.goldingmedia.goldingcloud;

public final class GpsNavigatorProtos {
  private GpsNavigatorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CGpsNavigatorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:goldingcloud.CGpsNavigator)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1:master,2:terminal,3:server
     * </pre>
     *
     * <code>int32 dev_type = 1;</code>
     */
    int getDevType();

    /**
     * <pre>
     *master device id
     * </pre>
     *
     * <code>string master_id = 2;</code>
     */
    java.lang.String getMasterId();
    /**
     * <pre>
     *master device id
     * </pre>
     *
     * <code>string master_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getMasterIdBytes();

    /**
     * <pre>
     *GPS longitude:112.259
     * </pre>
     *
     * <code>string longitude = 3;</code>
     */
    java.lang.String getLongitude();
    /**
     * <pre>
     *GPS longitude:112.259
     * </pre>
     *
     * <code>string longitude = 3;</code>
     */
    com.google.protobuf.ByteString
        getLongitudeBytes();

    /**
     * <pre>
     *GPS latitude:78.136
     * </pre>
     *
     * <code>string latitude = 4;</code>
     */
    java.lang.String getLatitude();
    /**
     * <pre>
     *GPS latitude:78.136
     * </pre>
     *
     * <code>string latitude = 4;</code>
     */
    com.google.protobuf.ByteString
        getLatitudeBytes();

    /**
     * <pre>
     *time_t
     * </pre>
     *
     * <code>string gps_time = 5;</code>
     */
    java.lang.String getGpsTime();
    /**
     * <pre>
     *time_t
     * </pre>
     *
     * <code>string gps_time = 5;</code>
     */
    com.google.protobuf.ByteString
        getGpsTimeBytes();

    /**
     * <code>string country = 6;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>string country = 6;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>string province = 7;</code>
     */
    java.lang.String getProvince();
    /**
     * <code>string province = 7;</code>
     */
    com.google.protobuf.ByteString
        getProvinceBytes();

    /**
     * <code>string city = 8;</code>
     */
    java.lang.String getCity();
    /**
     * <code>string city = 8;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>string district = 9;</code>
     */
    java.lang.String getDistrict();
    /**
     * <code>string district = 9;</code>
     */
    com.google.protobuf.ByteString
        getDistrictBytes();

    /**
     * <code>string weather = 10;</code>
     */
    java.lang.String getWeather();
    /**
     * <code>string weather = 10;</code>
     */
    com.google.protobuf.ByteString
        getWeatherBytes();
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code goldingcloud.CGpsNavigator}
   */
  public  static final class CGpsNavigator extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:goldingcloud.CGpsNavigator)
      CGpsNavigatorOrBuilder {
    // Use CGpsNavigator.newBuilder() to construct.
    private CGpsNavigator(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CGpsNavigator() {
      devType_ = 0;
      masterId_ = "";
      longitude_ = "";
      latitude_ = "";
      gpsTime_ = "";
      country_ = "";
      province_ = "";
      city_ = "";
      district_ = "";
      weather_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CGpsNavigator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              devType_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              masterId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              longitude_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              latitude_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              gpsTime_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              province_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              district_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              weather_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.goldingmedia.goldingcloud.GpsNavigatorProtos.internal_static_goldingcloud_CGpsNavigator_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.goldingmedia.goldingcloud.GpsNavigatorProtos.internal_static_goldingcloud_CGpsNavigator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator.class, com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator.Builder.class);
    }

    public static final int DEV_TYPE_FIELD_NUMBER = 1;
    private int devType_;
    /**
     * <pre>
     *1:master,2:terminal,3:server
     * </pre>
     *
     * <code>int32 dev_type = 1;</code>
     */
    public int getDevType() {
      return devType_;
    }

    public static final int MASTER_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object masterId_;
    /**
     * <pre>
     *master device id
     * </pre>
     *
     * <code>string master_id = 2;</code>
     */
    public java.lang.String getMasterId() {
      java.lang.Object ref = masterId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        masterId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *master device id
     * </pre>
     *
     * <code>string master_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMasterIdBytes() {
      java.lang.Object ref = masterId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        masterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGITUDE_FIELD_NUMBER = 3;
    private volatile java.lang.Object longitude_;
    /**
     * <pre>
     *GPS longitude:112.259
     * </pre>
     *
     * <code>string longitude = 3;</code>
     */
    public java.lang.String getLongitude() {
      java.lang.Object ref = longitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        longitude_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *GPS longitude:112.259
     * </pre>
     *
     * <code>string longitude = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLongitudeBytes() {
      java.lang.Object ref = longitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 4;
    private volatile java.lang.Object latitude_;
    /**
     * <pre>
     *GPS latitude:78.136
     * </pre>
     *
     * <code>string latitude = 4;</code>
     */
    public java.lang.String getLatitude() {
      java.lang.Object ref = latitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        latitude_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *GPS latitude:78.136
     * </pre>
     *
     * <code>string latitude = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLatitudeBytes() {
      java.lang.Object ref = latitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        latitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GPS_TIME_FIELD_NUMBER = 5;
    private volatile java.lang.Object gpsTime_;
    /**
     * <pre>
     *time_t
     * </pre>
     *
     * <code>string gps_time = 5;</code>
     */
    public java.lang.String getGpsTime() {
      java.lang.Object ref = gpsTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gpsTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *time_t
     * </pre>
     *
     * <code>string gps_time = 5;</code>
     */
    public com.google.protobuf.ByteString
        getGpsTimeBytes() {
      java.lang.Object ref = gpsTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gpsTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 6;
    private volatile java.lang.Object country_;
    /**
     * <code>string country = 6;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>string country = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROVINCE_FIELD_NUMBER = 7;
    private volatile java.lang.Object province_;
    /**
     * <code>string province = 7;</code>
     */
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        province_ = s;
        return s;
      }
    }
    /**
     * <code>string province = 7;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 8;
    private volatile java.lang.Object city_;
    /**
     * <code>string city = 8;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISTRICT_FIELD_NUMBER = 9;
    private volatile java.lang.Object district_;
    /**
     * <code>string district = 9;</code>
     */
    public java.lang.String getDistrict() {
      java.lang.Object ref = district_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        district_ = s;
        return s;
      }
    }
    /**
     * <code>string district = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDistrictBytes() {
      java.lang.Object ref = district_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        district_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEATHER_FIELD_NUMBER = 10;
    private volatile java.lang.Object weather_;
    /**
     * <code>string weather = 10;</code>
     */
    public java.lang.String getWeather() {
      java.lang.Object ref = weather_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weather_ = s;
        return s;
      }
    }
    /**
     * <code>string weather = 10;</code>
     */
    public com.google.protobuf.ByteString
        getWeatherBytes() {
      java.lang.Object ref = weather_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weather_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (devType_ != 0) {
        output.writeInt32(1, devType_);
      }
      if (!getMasterIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, masterId_);
      }
      if (!getLongitudeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, longitude_);
      }
      if (!getLatitudeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, latitude_);
      }
      if (!getGpsTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, gpsTime_);
      }
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, country_);
      }
      if (!getProvinceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, province_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, city_);
      }
      if (!getDistrictBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, district_);
      }
      if (!getWeatherBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, weather_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (devType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, devType_);
      }
      if (!getMasterIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, masterId_);
      }
      if (!getLongitudeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, longitude_);
      }
      if (!getLatitudeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, latitude_);
      }
      if (!getGpsTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, gpsTime_);
      }
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, country_);
      }
      if (!getProvinceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, province_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, city_);
      }
      if (!getDistrictBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, district_);
      }
      if (!getWeatherBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, weather_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator)) {
        return super.equals(obj);
      }
      com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator other = (com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator) obj;

      boolean result = true;
      result = result && (getDevType()
          == other.getDevType());
      result = result && getMasterId()
          .equals(other.getMasterId());
      result = result && getLongitude()
          .equals(other.getLongitude());
      result = result && getLatitude()
          .equals(other.getLatitude());
      result = result && getGpsTime()
          .equals(other.getGpsTime());
      result = result && getCountry()
          .equals(other.getCountry());
      result = result && getProvince()
          .equals(other.getProvince());
      result = result && getCity()
          .equals(other.getCity());
      result = result && getDistrict()
          .equals(other.getDistrict());
      result = result && getWeather()
          .equals(other.getWeather());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEV_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDevType();
      hash = (37 * hash) + MASTER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMasterId().hashCode();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLongitude().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLatitude().hashCode();
      hash = (37 * hash) + GPS_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getGpsTime().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
      hash = (53 * hash) + getProvince().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + DISTRICT_FIELD_NUMBER;
      hash = (53 * hash) + getDistrict().hashCode();
      hash = (37 * hash) + WEATHER_FIELD_NUMBER;
      hash = (53 * hash) + getWeather().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code goldingcloud.CGpsNavigator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:goldingcloud.CGpsNavigator)
        com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigatorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.goldingmedia.goldingcloud.GpsNavigatorProtos.internal_static_goldingcloud_CGpsNavigator_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.goldingmedia.goldingcloud.GpsNavigatorProtos.internal_static_goldingcloud_CGpsNavigator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator.class, com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator.Builder.class);
      }

      // Construct using com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        devType_ = 0;

        masterId_ = "";

        longitude_ = "";

        latitude_ = "";

        gpsTime_ = "";

        country_ = "";

        province_ = "";

        city_ = "";

        district_ = "";

        weather_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.goldingmedia.goldingcloud.GpsNavigatorProtos.internal_static_goldingcloud_CGpsNavigator_descriptor;
      }

      public com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator getDefaultInstanceForType() {
        return com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator.getDefaultInstance();
      }

      public com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator build() {
        com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator buildPartial() {
        com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator result = new com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator(this);
        result.devType_ = devType_;
        result.masterId_ = masterId_;
        result.longitude_ = longitude_;
        result.latitude_ = latitude_;
        result.gpsTime_ = gpsTime_;
        result.country_ = country_;
        result.province_ = province_;
        result.city_ = city_;
        result.district_ = district_;
        result.weather_ = weather_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator) {
          return mergeFrom((com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator other) {
        if (other == com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator.getDefaultInstance()) return this;
        if (other.getDevType() != 0) {
          setDevType(other.getDevType());
        }
        if (!other.getMasterId().isEmpty()) {
          masterId_ = other.masterId_;
          onChanged();
        }
        if (!other.getLongitude().isEmpty()) {
          longitude_ = other.longitude_;
          onChanged();
        }
        if (!other.getLatitude().isEmpty()) {
          latitude_ = other.latitude_;
          onChanged();
        }
        if (!other.getGpsTime().isEmpty()) {
          gpsTime_ = other.gpsTime_;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        if (!other.getProvince().isEmpty()) {
          province_ = other.province_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (!other.getDistrict().isEmpty()) {
          district_ = other.district_;
          onChanged();
        }
        if (!other.getWeather().isEmpty()) {
          weather_ = other.weather_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int devType_ ;
      /**
       * <pre>
       *1:master,2:terminal,3:server
       * </pre>
       *
       * <code>int32 dev_type = 1;</code>
       */
      public int getDevType() {
        return devType_;
      }
      /**
       * <pre>
       *1:master,2:terminal,3:server
       * </pre>
       *
       * <code>int32 dev_type = 1;</code>
       */
      public Builder setDevType(int value) {
        
        devType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1:master,2:terminal,3:server
       * </pre>
       *
       * <code>int32 dev_type = 1;</code>
       */
      public Builder clearDevType() {
        
        devType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object masterId_ = "";
      /**
       * <pre>
       *master device id
       * </pre>
       *
       * <code>string master_id = 2;</code>
       */
      public java.lang.String getMasterId() {
        java.lang.Object ref = masterId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          masterId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *master device id
       * </pre>
       *
       * <code>string master_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMasterIdBytes() {
        java.lang.Object ref = masterId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          masterId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *master device id
       * </pre>
       *
       * <code>string master_id = 2;</code>
       */
      public Builder setMasterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        masterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *master device id
       * </pre>
       *
       * <code>string master_id = 2;</code>
       */
      public Builder clearMasterId() {
        
        masterId_ = getDefaultInstance().getMasterId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *master device id
       * </pre>
       *
       * <code>string master_id = 2;</code>
       */
      public Builder setMasterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        masterId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object longitude_ = "";
      /**
       * <pre>
       *GPS longitude:112.259
       * </pre>
       *
       * <code>string longitude = 3;</code>
       */
      public java.lang.String getLongitude() {
        java.lang.Object ref = longitude_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          longitude_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *GPS longitude:112.259
       * </pre>
       *
       * <code>string longitude = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLongitudeBytes() {
        java.lang.Object ref = longitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          longitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *GPS longitude:112.259
       * </pre>
       *
       * <code>string longitude = 3;</code>
       */
      public Builder setLongitude(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *GPS longitude:112.259
       * </pre>
       *
       * <code>string longitude = 3;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = getDefaultInstance().getLongitude();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *GPS longitude:112.259
       * </pre>
       *
       * <code>string longitude = 3;</code>
       */
      public Builder setLongitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        longitude_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object latitude_ = "";
      /**
       * <pre>
       *GPS latitude:78.136
       * </pre>
       *
       * <code>string latitude = 4;</code>
       */
      public java.lang.String getLatitude() {
        java.lang.Object ref = latitude_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          latitude_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *GPS latitude:78.136
       * </pre>
       *
       * <code>string latitude = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLatitudeBytes() {
        java.lang.Object ref = latitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          latitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *GPS latitude:78.136
       * </pre>
       *
       * <code>string latitude = 4;</code>
       */
      public Builder setLatitude(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *GPS latitude:78.136
       * </pre>
       *
       * <code>string latitude = 4;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = getDefaultInstance().getLatitude();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *GPS latitude:78.136
       * </pre>
       *
       * <code>string latitude = 4;</code>
       */
      public Builder setLatitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        latitude_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gpsTime_ = "";
      /**
       * <pre>
       *time_t
       * </pre>
       *
       * <code>string gps_time = 5;</code>
       */
      public java.lang.String getGpsTime() {
        java.lang.Object ref = gpsTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gpsTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *time_t
       * </pre>
       *
       * <code>string gps_time = 5;</code>
       */
      public com.google.protobuf.ByteString
          getGpsTimeBytes() {
        java.lang.Object ref = gpsTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gpsTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *time_t
       * </pre>
       *
       * <code>string gps_time = 5;</code>
       */
      public Builder setGpsTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gpsTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *time_t
       * </pre>
       *
       * <code>string gps_time = 5;</code>
       */
      public Builder clearGpsTime() {
        
        gpsTime_ = getDefaultInstance().getGpsTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *time_t
       * </pre>
       *
       * <code>string gps_time = 5;</code>
       */
      public Builder setGpsTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gpsTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>string country = 6;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country = 6;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string country = 6;</code>
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>string country = 6;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object province_ = "";
      /**
       * <code>string province = 7;</code>
       */
      public java.lang.String getProvince() {
        java.lang.Object ref = province_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          province_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string province = 7;</code>
       */
      public com.google.protobuf.ByteString
          getProvinceBytes() {
        java.lang.Object ref = province_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          province_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string province = 7;</code>
       */
      public Builder setProvince(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        province_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string province = 7;</code>
       */
      public Builder clearProvince() {
        
        province_ = getDefaultInstance().getProvince();
        onChanged();
        return this;
      }
      /**
       * <code>string province = 7;</code>
       */
      public Builder setProvinceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        province_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 8;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 8;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 8;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>string city = 8;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object district_ = "";
      /**
       * <code>string district = 9;</code>
       */
      public java.lang.String getDistrict() {
        java.lang.Object ref = district_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          district_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string district = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDistrictBytes() {
        java.lang.Object ref = district_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          district_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string district = 9;</code>
       */
      public Builder setDistrict(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        district_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string district = 9;</code>
       */
      public Builder clearDistrict() {
        
        district_ = getDefaultInstance().getDistrict();
        onChanged();
        return this;
      }
      /**
       * <code>string district = 9;</code>
       */
      public Builder setDistrictBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        district_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object weather_ = "";
      /**
       * <code>string weather = 10;</code>
       */
      public java.lang.String getWeather() {
        java.lang.Object ref = weather_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weather_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string weather = 10;</code>
       */
      public com.google.protobuf.ByteString
          getWeatherBytes() {
        java.lang.Object ref = weather_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weather_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string weather = 10;</code>
       */
      public Builder setWeather(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weather_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string weather = 10;</code>
       */
      public Builder clearWeather() {
        
        weather_ = getDefaultInstance().getWeather();
        onChanged();
        return this;
      }
      /**
       * <code>string weather = 10;</code>
       */
      public Builder setWeatherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weather_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:goldingcloud.CGpsNavigator)
    }

    // @@protoc_insertion_point(class_scope:goldingcloud.CGpsNavigator)
    private static final com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator();
    }

    public static com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CGpsNavigator>
        PARSER = new com.google.protobuf.AbstractParser<CGpsNavigator>() {
      public CGpsNavigator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CGpsNavigator(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CGpsNavigator> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CGpsNavigator> getParserForType() {
      return PARSER;
    }

    public com.goldingmedia.goldingcloud.GpsNavigatorProtos.CGpsNavigator getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_goldingcloud_CGpsNavigator_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_goldingcloud_CGpsNavigator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022GpsNavigator.proto\022\014goldingcloud\"\277\001\n\rC" +
      "GpsNavigator\022\020\n\010dev_type\030\001 \001(\005\022\021\n\tmaster" +
      "_id\030\002 \001(\t\022\021\n\tlongitude\030\003 \001(\t\022\020\n\010latitude" +
      "\030\004 \001(\t\022\020\n\010gps_time\030\005 \001(\t\022\017\n\007country\030\006 \001(" +
      "\t\022\020\n\010province\030\007 \001(\t\022\014\n\004city\030\010 \001(\t\022\020\n\010dis" +
      "trict\030\t \001(\t\022\017\n\007weather\030\n \001(\tBf\n\035com.gold" +
      "ingmedia.goldingcloudB\022GpsNavigatorProto" +
      "s\252\0020com.goldingmedia.goldingcloud.GpsNav" +
      "igatorProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_goldingcloud_CGpsNavigator_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_goldingcloud_CGpsNavigator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_goldingcloud_CGpsNavigator_descriptor,
        new java.lang.String[] { "DevType", "MasterId", "Longitude", "Latitude", "GpsTime", "Country", "Province", "City", "District", "Weather", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
