// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Logon.proto

package com.goldingmedia.goldingcloud;

public final class LogonProtos {
  private LogonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CLogonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:goldingcloud.CLogon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.goldingcloud.CLogon.System_Node sys_obj = 1;</code>
     */
    int getSysObjValue();
    /**
     * <code>.goldingcloud.CLogon.System_Node sys_obj = 1;</code>
     */
    com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node getSysObj();

    /**
     * <pre>
     * device id (CPU serial)
     * </pre>
     *
     * <code>string dev_id = 2;</code>
     */
    java.lang.String getDevId();
    /**
     * <pre>
     * device id (CPU serial)
     * </pre>
     *
     * <code>string dev_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getDevIdBytes();

    /**
     * <pre>
     * master device id
     * </pre>
     *
     * <code>string master_id = 3;</code>
     */
    java.lang.String getMasterId();
    /**
     * <pre>
     * master device id
     * </pre>
     *
     * <code>string master_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getMasterIdBytes();

    /**
     * <pre>
     * for master and terminal is:admin
     * </pre>
     *
     * <code>string user_name = 4;</code>
     */
    java.lang.String getUserName();
    /**
     * <pre>
     * for master and terminal is:admin
     * </pre>
     *
     * <code>string user_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     * for master and terminal is:admin
     * </pre>
     *
     * <code>string user_pwd = 5;</code>
     */
    java.lang.String getUserPwd();
    /**
     * <pre>
     * for master and terminal is:admin
     * </pre>
     *
     * <code>string user_pwd = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserPwdBytes();

    /**
     * <pre>
     * default is:Guest
     * </pre>
     *
     * <code>string user_role = 6;</code>
     */
    java.lang.String getUserRole();
    /**
     * <pre>
     * default is:Guest
     * </pre>
     *
     * <code>string user_role = 6;</code>
     */
    com.google.protobuf.ByteString
        getUserRoleBytes();

    /**
     * <pre>
     *  The Administrator/Backup/Users/Network Configure/Guest Group
     * </pre>
     *
     * <code>string user_group = 7;</code>
     */
    java.lang.String getUserGroup();
    /**
     * <pre>
     *  The Administrator/Backup/Users/Network Configure/Guest Group
     * </pre>
     *
     * <code>string user_group = 7;</code>
     */
    com.google.protobuf.ByteString
        getUserGroupBytes();

    /**
     * <pre>
     * user mobile number
     * </pre>
     *
     * <code>string user_mobile = 8;</code>
     */
    java.lang.String getUserMobile();
    /**
     * <pre>
     * user mobile number
     * </pre>
     *
     * <code>string user_mobile = 8;</code>
     */
    com.google.protobuf.ByteString
        getUserMobileBytes();

    /**
     * <code>string simcard_iccid = 9;</code>
     */
    java.lang.String getSimcardIccid();
    /**
     * <code>string simcard_iccid = 9;</code>
     */
    com.google.protobuf.ByteString
        getSimcardIccidBytes();

    /**
     * <pre>
     *default number:0
     * </pre>
     *
     * <code>string master_number = 10;</code>
     */
    java.lang.String getMasterNumber();
    /**
     * <pre>
     *default number:0
     * </pre>
     *
     * <code>string master_number = 10;</code>
     */
    com.google.protobuf.ByteString
        getMasterNumberBytes();
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code goldingcloud.CLogon}
   */
  public  static final class CLogon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:goldingcloud.CLogon)
      CLogonOrBuilder {
    // Use CLogon.newBuilder() to construct.
    private CLogon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CLogon() {
      sysObj_ = 0;
      devId_ = "";
      masterId_ = "";
      userName_ = "";
      userPwd_ = "";
      userRole_ = "";
      userGroup_ = "";
      userMobile_ = "";
      simcardIccid_ = "";
      masterNumber_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CLogon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              sysObj_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              devId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              masterId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              userPwd_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              userRole_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              userGroup_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              userMobile_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              simcardIccid_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              masterNumber_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.goldingmedia.goldingcloud.LogonProtos.internal_static_goldingcloud_CLogon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.goldingmedia.goldingcloud.LogonProtos.internal_static_goldingcloud_CLogon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.goldingmedia.goldingcloud.LogonProtos.CLogon.class, com.goldingmedia.goldingcloud.LogonProtos.CLogon.Builder.class);
    }

    /**
     * Protobuf enum {@code goldingcloud.CLogon.System_Node}
     */
    public enum System_Node
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNIVERSAL = 0;</code>
       */
      UNIVERSAL(0),
      /**
       * <code>MASTER = 1;</code>
       */
      MASTER(1),
      /**
       * <code>TERMINAL = 2;</code>
       */
      TERMINAL(2),
      /**
       * <code>SERVER = 3;</code>
       */
      SERVER(3),
      /**
       * <code>WEBBROWSER = 4;</code>
       */
      WEBBROWSER(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNIVERSAL = 0;</code>
       */
      public static final int UNIVERSAL_VALUE = 0;
      /**
       * <code>MASTER = 1;</code>
       */
      public static final int MASTER_VALUE = 1;
      /**
       * <code>TERMINAL = 2;</code>
       */
      public static final int TERMINAL_VALUE = 2;
      /**
       * <code>SERVER = 3;</code>
       */
      public static final int SERVER_VALUE = 3;
      /**
       * <code>WEBBROWSER = 4;</code>
       */
      public static final int WEBBROWSER_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static System_Node valueOf(int value) {
        return forNumber(value);
      }

      public static System_Node forNumber(int value) {
        switch (value) {
          case 0: return UNIVERSAL;
          case 1: return MASTER;
          case 2: return TERMINAL;
          case 3: return SERVER;
          case 4: return WEBBROWSER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<System_Node>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          System_Node> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<System_Node>() {
              public System_Node findValueByNumber(int number) {
                return System_Node.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.goldingmedia.goldingcloud.LogonProtos.CLogon.getDescriptor().getEnumTypes().get(0);
      }

      private static final System_Node[] VALUES = values();

      public static System_Node valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private System_Node(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:goldingcloud.CLogon.System_Node)
    }

    public static final int SYS_OBJ_FIELD_NUMBER = 1;
    private int sysObj_;
    /**
     * <code>.goldingcloud.CLogon.System_Node sys_obj = 1;</code>
     */
    public int getSysObjValue() {
      return sysObj_;
    }
    /**
     * <code>.goldingcloud.CLogon.System_Node sys_obj = 1;</code>
     */
    public com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node getSysObj() {
      com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node result = com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node.valueOf(sysObj_);
      return result == null ? com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node.UNRECOGNIZED : result;
    }

    public static final int DEV_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object devId_;
    /**
     * <pre>
     * device id (CPU serial)
     * </pre>
     *
     * <code>string dev_id = 2;</code>
     */
    public java.lang.String getDevId() {
      java.lang.Object ref = devId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        devId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * device id (CPU serial)
     * </pre>
     *
     * <code>string dev_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDevIdBytes() {
      java.lang.Object ref = devId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        devId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MASTER_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object masterId_;
    /**
     * <pre>
     * master device id
     * </pre>
     *
     * <code>string master_id = 3;</code>
     */
    public java.lang.String getMasterId() {
      java.lang.Object ref = masterId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        masterId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * master device id
     * </pre>
     *
     * <code>string master_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMasterIdBytes() {
      java.lang.Object ref = masterId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        masterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object userName_;
    /**
     * <pre>
     * for master and terminal is:admin
     * </pre>
     *
     * <code>string user_name = 4;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * for master and terminal is:admin
     * </pre>
     *
     * <code>string user_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_PWD_FIELD_NUMBER = 5;
    private volatile java.lang.Object userPwd_;
    /**
     * <pre>
     * for master and terminal is:admin
     * </pre>
     *
     * <code>string user_pwd = 5;</code>
     */
    public java.lang.String getUserPwd() {
      java.lang.Object ref = userPwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPwd_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * for master and terminal is:admin
     * </pre>
     *
     * <code>string user_pwd = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserPwdBytes() {
      java.lang.Object ref = userPwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ROLE_FIELD_NUMBER = 6;
    private volatile java.lang.Object userRole_;
    /**
     * <pre>
     * default is:Guest
     * </pre>
     *
     * <code>string user_role = 6;</code>
     */
    public java.lang.String getUserRole() {
      java.lang.Object ref = userRole_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userRole_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * default is:Guest
     * </pre>
     *
     * <code>string user_role = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserRoleBytes() {
      java.lang.Object ref = userRole_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userRole_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_GROUP_FIELD_NUMBER = 7;
    private volatile java.lang.Object userGroup_;
    /**
     * <pre>
     *  The Administrator/Backup/Users/Network Configure/Guest Group
     * </pre>
     *
     * <code>string user_group = 7;</code>
     */
    public java.lang.String getUserGroup() {
      java.lang.Object ref = userGroup_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userGroup_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  The Administrator/Backup/Users/Network Configure/Guest Group
     * </pre>
     *
     * <code>string user_group = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUserGroupBytes() {
      java.lang.Object ref = userGroup_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userGroup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_MOBILE_FIELD_NUMBER = 8;
    private volatile java.lang.Object userMobile_;
    /**
     * <pre>
     * user mobile number
     * </pre>
     *
     * <code>string user_mobile = 8;</code>
     */
    public java.lang.String getUserMobile() {
      java.lang.Object ref = userMobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userMobile_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * user mobile number
     * </pre>
     *
     * <code>string user_mobile = 8;</code>
     */
    public com.google.protobuf.ByteString
        getUserMobileBytes() {
      java.lang.Object ref = userMobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userMobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIMCARD_ICCID_FIELD_NUMBER = 9;
    private volatile java.lang.Object simcardIccid_;
    /**
     * <code>string simcard_iccid = 9;</code>
     */
    public java.lang.String getSimcardIccid() {
      java.lang.Object ref = simcardIccid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        simcardIccid_ = s;
        return s;
      }
    }
    /**
     * <code>string simcard_iccid = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSimcardIccidBytes() {
      java.lang.Object ref = simcardIccid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        simcardIccid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MASTER_NUMBER_FIELD_NUMBER = 10;
    private volatile java.lang.Object masterNumber_;
    /**
     * <pre>
     *default number:0
     * </pre>
     *
     * <code>string master_number = 10;</code>
     */
    public java.lang.String getMasterNumber() {
      java.lang.Object ref = masterNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        masterNumber_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *default number:0
     * </pre>
     *
     * <code>string master_number = 10;</code>
     */
    public com.google.protobuf.ByteString
        getMasterNumberBytes() {
      java.lang.Object ref = masterNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        masterNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sysObj_ != com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node.UNIVERSAL.getNumber()) {
        output.writeEnum(1, sysObj_);
      }
      if (!getDevIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, devId_);
      }
      if (!getMasterIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, masterId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userName_);
      }
      if (!getUserPwdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userPwd_);
      }
      if (!getUserRoleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userRole_);
      }
      if (!getUserGroupBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, userGroup_);
      }
      if (!getUserMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, userMobile_);
      }
      if (!getSimcardIccidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, simcardIccid_);
      }
      if (!getMasterNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, masterNumber_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sysObj_ != com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node.UNIVERSAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, sysObj_);
      }
      if (!getDevIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, devId_);
      }
      if (!getMasterIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, masterId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userName_);
      }
      if (!getUserPwdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userPwd_);
      }
      if (!getUserRoleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userRole_);
      }
      if (!getUserGroupBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, userGroup_);
      }
      if (!getUserMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, userMobile_);
      }
      if (!getSimcardIccidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, simcardIccid_);
      }
      if (!getMasterNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, masterNumber_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.goldingmedia.goldingcloud.LogonProtos.CLogon)) {
        return super.equals(obj);
      }
      com.goldingmedia.goldingcloud.LogonProtos.CLogon other = (com.goldingmedia.goldingcloud.LogonProtos.CLogon) obj;

      boolean result = true;
      result = result && sysObj_ == other.sysObj_;
      result = result && getDevId()
          .equals(other.getDevId());
      result = result && getMasterId()
          .equals(other.getMasterId());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getUserPwd()
          .equals(other.getUserPwd());
      result = result && getUserRole()
          .equals(other.getUserRole());
      result = result && getUserGroup()
          .equals(other.getUserGroup());
      result = result && getUserMobile()
          .equals(other.getUserMobile());
      result = result && getSimcardIccid()
          .equals(other.getSimcardIccid());
      result = result && getMasterNumber()
          .equals(other.getMasterNumber());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SYS_OBJ_FIELD_NUMBER;
      hash = (53 * hash) + sysObj_;
      hash = (37 * hash) + DEV_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDevId().hashCode();
      hash = (37 * hash) + MASTER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMasterId().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + USER_PWD_FIELD_NUMBER;
      hash = (53 * hash) + getUserPwd().hashCode();
      hash = (37 * hash) + USER_ROLE_FIELD_NUMBER;
      hash = (53 * hash) + getUserRole().hashCode();
      hash = (37 * hash) + USER_GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getUserGroup().hashCode();
      hash = (37 * hash) + USER_MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getUserMobile().hashCode();
      hash = (37 * hash) + SIMCARD_ICCID_FIELD_NUMBER;
      hash = (53 * hash) + getSimcardIccid().hashCode();
      hash = (37 * hash) + MASTER_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMasterNumber().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.goldingmedia.goldingcloud.LogonProtos.CLogon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code goldingcloud.CLogon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:goldingcloud.CLogon)
        com.goldingmedia.goldingcloud.LogonProtos.CLogonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.goldingmedia.goldingcloud.LogonProtos.internal_static_goldingcloud_CLogon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.goldingmedia.goldingcloud.LogonProtos.internal_static_goldingcloud_CLogon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.goldingmedia.goldingcloud.LogonProtos.CLogon.class, com.goldingmedia.goldingcloud.LogonProtos.CLogon.Builder.class);
      }

      // Construct using com.goldingmedia.goldingcloud.LogonProtos.CLogon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sysObj_ = 0;

        devId_ = "";

        masterId_ = "";

        userName_ = "";

        userPwd_ = "";

        userRole_ = "";

        userGroup_ = "";

        userMobile_ = "";

        simcardIccid_ = "";

        masterNumber_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.goldingmedia.goldingcloud.LogonProtos.internal_static_goldingcloud_CLogon_descriptor;
      }

      public com.goldingmedia.goldingcloud.LogonProtos.CLogon getDefaultInstanceForType() {
        return com.goldingmedia.goldingcloud.LogonProtos.CLogon.getDefaultInstance();
      }

      public com.goldingmedia.goldingcloud.LogonProtos.CLogon build() {
        com.goldingmedia.goldingcloud.LogonProtos.CLogon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.goldingmedia.goldingcloud.LogonProtos.CLogon buildPartial() {
        com.goldingmedia.goldingcloud.LogonProtos.CLogon result = new com.goldingmedia.goldingcloud.LogonProtos.CLogon(this);
        result.sysObj_ = sysObj_;
        result.devId_ = devId_;
        result.masterId_ = masterId_;
        result.userName_ = userName_;
        result.userPwd_ = userPwd_;
        result.userRole_ = userRole_;
        result.userGroup_ = userGroup_;
        result.userMobile_ = userMobile_;
        result.simcardIccid_ = simcardIccid_;
        result.masterNumber_ = masterNumber_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.goldingmedia.goldingcloud.LogonProtos.CLogon) {
          return mergeFrom((com.goldingmedia.goldingcloud.LogonProtos.CLogon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.goldingmedia.goldingcloud.LogonProtos.CLogon other) {
        if (other == com.goldingmedia.goldingcloud.LogonProtos.CLogon.getDefaultInstance()) return this;
        if (other.sysObj_ != 0) {
          setSysObjValue(other.getSysObjValue());
        }
        if (!other.getDevId().isEmpty()) {
          devId_ = other.devId_;
          onChanged();
        }
        if (!other.getMasterId().isEmpty()) {
          masterId_ = other.masterId_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getUserPwd().isEmpty()) {
          userPwd_ = other.userPwd_;
          onChanged();
        }
        if (!other.getUserRole().isEmpty()) {
          userRole_ = other.userRole_;
          onChanged();
        }
        if (!other.getUserGroup().isEmpty()) {
          userGroup_ = other.userGroup_;
          onChanged();
        }
        if (!other.getUserMobile().isEmpty()) {
          userMobile_ = other.userMobile_;
          onChanged();
        }
        if (!other.getSimcardIccid().isEmpty()) {
          simcardIccid_ = other.simcardIccid_;
          onChanged();
        }
        if (!other.getMasterNumber().isEmpty()) {
          masterNumber_ = other.masterNumber_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.goldingmedia.goldingcloud.LogonProtos.CLogon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.goldingmedia.goldingcloud.LogonProtos.CLogon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sysObj_ = 0;
      /**
       * <code>.goldingcloud.CLogon.System_Node sys_obj = 1;</code>
       */
      public int getSysObjValue() {
        return sysObj_;
      }
      /**
       * <code>.goldingcloud.CLogon.System_Node sys_obj = 1;</code>
       */
      public Builder setSysObjValue(int value) {
        sysObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.goldingcloud.CLogon.System_Node sys_obj = 1;</code>
       */
      public com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node getSysObj() {
        com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node result = com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node.valueOf(sysObj_);
        return result == null ? com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node.UNRECOGNIZED : result;
      }
      /**
       * <code>.goldingcloud.CLogon.System_Node sys_obj = 1;</code>
       */
      public Builder setSysObj(com.goldingmedia.goldingcloud.LogonProtos.CLogon.System_Node value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sysObj_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.goldingcloud.CLogon.System_Node sys_obj = 1;</code>
       */
      public Builder clearSysObj() {
        
        sysObj_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object devId_ = "";
      /**
       * <pre>
       * device id (CPU serial)
       * </pre>
       *
       * <code>string dev_id = 2;</code>
       */
      public java.lang.String getDevId() {
        java.lang.Object ref = devId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          devId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * device id (CPU serial)
       * </pre>
       *
       * <code>string dev_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDevIdBytes() {
        java.lang.Object ref = devId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          devId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * device id (CPU serial)
       * </pre>
       *
       * <code>string dev_id = 2;</code>
       */
      public Builder setDevId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        devId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * device id (CPU serial)
       * </pre>
       *
       * <code>string dev_id = 2;</code>
       */
      public Builder clearDevId() {
        
        devId_ = getDefaultInstance().getDevId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * device id (CPU serial)
       * </pre>
       *
       * <code>string dev_id = 2;</code>
       */
      public Builder setDevIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        devId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object masterId_ = "";
      /**
       * <pre>
       * master device id
       * </pre>
       *
       * <code>string master_id = 3;</code>
       */
      public java.lang.String getMasterId() {
        java.lang.Object ref = masterId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          masterId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * master device id
       * </pre>
       *
       * <code>string master_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMasterIdBytes() {
        java.lang.Object ref = masterId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          masterId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * master device id
       * </pre>
       *
       * <code>string master_id = 3;</code>
       */
      public Builder setMasterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        masterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * master device id
       * </pre>
       *
       * <code>string master_id = 3;</code>
       */
      public Builder clearMasterId() {
        
        masterId_ = getDefaultInstance().getMasterId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * master device id
       * </pre>
       *
       * <code>string master_id = 3;</code>
       */
      public Builder setMasterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        masterId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <pre>
       * for master and terminal is:admin
       * </pre>
       *
       * <code>string user_name = 4;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * for master and terminal is:admin
       * </pre>
       *
       * <code>string user_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * for master and terminal is:admin
       * </pre>
       *
       * <code>string user_name = 4;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * for master and terminal is:admin
       * </pre>
       *
       * <code>string user_name = 4;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * for master and terminal is:admin
       * </pre>
       *
       * <code>string user_name = 4;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPwd_ = "";
      /**
       * <pre>
       * for master and terminal is:admin
       * </pre>
       *
       * <code>string user_pwd = 5;</code>
       */
      public java.lang.String getUserPwd() {
        java.lang.Object ref = userPwd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPwd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * for master and terminal is:admin
       * </pre>
       *
       * <code>string user_pwd = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserPwdBytes() {
        java.lang.Object ref = userPwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * for master and terminal is:admin
       * </pre>
       *
       * <code>string user_pwd = 5;</code>
       */
      public Builder setUserPwd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userPwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * for master and terminal is:admin
       * </pre>
       *
       * <code>string user_pwd = 5;</code>
       */
      public Builder clearUserPwd() {
        
        userPwd_ = getDefaultInstance().getUserPwd();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * for master and terminal is:admin
       * </pre>
       *
       * <code>string user_pwd = 5;</code>
       */
      public Builder setUserPwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userPwd_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userRole_ = "";
      /**
       * <pre>
       * default is:Guest
       * </pre>
       *
       * <code>string user_role = 6;</code>
       */
      public java.lang.String getUserRole() {
        java.lang.Object ref = userRole_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userRole_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * default is:Guest
       * </pre>
       *
       * <code>string user_role = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUserRoleBytes() {
        java.lang.Object ref = userRole_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userRole_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * default is:Guest
       * </pre>
       *
       * <code>string user_role = 6;</code>
       */
      public Builder setUserRole(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userRole_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * default is:Guest
       * </pre>
       *
       * <code>string user_role = 6;</code>
       */
      public Builder clearUserRole() {
        
        userRole_ = getDefaultInstance().getUserRole();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * default is:Guest
       * </pre>
       *
       * <code>string user_role = 6;</code>
       */
      public Builder setUserRoleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userRole_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userGroup_ = "";
      /**
       * <pre>
       *  The Administrator/Backup/Users/Network Configure/Guest Group
       * </pre>
       *
       * <code>string user_group = 7;</code>
       */
      public java.lang.String getUserGroup() {
        java.lang.Object ref = userGroup_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userGroup_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  The Administrator/Backup/Users/Network Configure/Guest Group
       * </pre>
       *
       * <code>string user_group = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUserGroupBytes() {
        java.lang.Object ref = userGroup_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userGroup_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  The Administrator/Backup/Users/Network Configure/Guest Group
       * </pre>
       *
       * <code>string user_group = 7;</code>
       */
      public Builder setUserGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userGroup_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  The Administrator/Backup/Users/Network Configure/Guest Group
       * </pre>
       *
       * <code>string user_group = 7;</code>
       */
      public Builder clearUserGroup() {
        
        userGroup_ = getDefaultInstance().getUserGroup();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  The Administrator/Backup/Users/Network Configure/Guest Group
       * </pre>
       *
       * <code>string user_group = 7;</code>
       */
      public Builder setUserGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userGroup_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userMobile_ = "";
      /**
       * <pre>
       * user mobile number
       * </pre>
       *
       * <code>string user_mobile = 8;</code>
       */
      public java.lang.String getUserMobile() {
        java.lang.Object ref = userMobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userMobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * user mobile number
       * </pre>
       *
       * <code>string user_mobile = 8;</code>
       */
      public com.google.protobuf.ByteString
          getUserMobileBytes() {
        java.lang.Object ref = userMobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userMobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * user mobile number
       * </pre>
       *
       * <code>string user_mobile = 8;</code>
       */
      public Builder setUserMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userMobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * user mobile number
       * </pre>
       *
       * <code>string user_mobile = 8;</code>
       */
      public Builder clearUserMobile() {
        
        userMobile_ = getDefaultInstance().getUserMobile();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * user mobile number
       * </pre>
       *
       * <code>string user_mobile = 8;</code>
       */
      public Builder setUserMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userMobile_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object simcardIccid_ = "";
      /**
       * <code>string simcard_iccid = 9;</code>
       */
      public java.lang.String getSimcardIccid() {
        java.lang.Object ref = simcardIccid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          simcardIccid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string simcard_iccid = 9;</code>
       */
      public com.google.protobuf.ByteString
          getSimcardIccidBytes() {
        java.lang.Object ref = simcardIccid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          simcardIccid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string simcard_iccid = 9;</code>
       */
      public Builder setSimcardIccid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        simcardIccid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string simcard_iccid = 9;</code>
       */
      public Builder clearSimcardIccid() {
        
        simcardIccid_ = getDefaultInstance().getSimcardIccid();
        onChanged();
        return this;
      }
      /**
       * <code>string simcard_iccid = 9;</code>
       */
      public Builder setSimcardIccidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        simcardIccid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object masterNumber_ = "";
      /**
       * <pre>
       *default number:0
       * </pre>
       *
       * <code>string master_number = 10;</code>
       */
      public java.lang.String getMasterNumber() {
        java.lang.Object ref = masterNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          masterNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *default number:0
       * </pre>
       *
       * <code>string master_number = 10;</code>
       */
      public com.google.protobuf.ByteString
          getMasterNumberBytes() {
        java.lang.Object ref = masterNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          masterNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *default number:0
       * </pre>
       *
       * <code>string master_number = 10;</code>
       */
      public Builder setMasterNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        masterNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *default number:0
       * </pre>
       *
       * <code>string master_number = 10;</code>
       */
      public Builder clearMasterNumber() {
        
        masterNumber_ = getDefaultInstance().getMasterNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *default number:0
       * </pre>
       *
       * <code>string master_number = 10;</code>
       */
      public Builder setMasterNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        masterNumber_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:goldingcloud.CLogon)
    }

    // @@protoc_insertion_point(class_scope:goldingcloud.CLogon)
    private static final com.goldingmedia.goldingcloud.LogonProtos.CLogon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.goldingmedia.goldingcloud.LogonProtos.CLogon();
    }

    public static com.goldingmedia.goldingcloud.LogonProtos.CLogon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CLogon>
        PARSER = new com.google.protobuf.AbstractParser<CLogon>() {
      public CLogon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CLogon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CLogon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CLogon> getParserForType() {
      return PARSER;
    }

    public com.goldingmedia.goldingcloud.LogonProtos.CLogon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_goldingcloud_CLogon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_goldingcloud_CLogon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Logon.proto\022\014goldingcloud\"\301\002\n\006CLogon\0221" +
      "\n\007sys_obj\030\001 \001(\0162 .goldingcloud.CLogon.Sy" +
      "stem_Node\022\016\n\006dev_id\030\002 \001(\t\022\021\n\tmaster_id\030\003" +
      " \001(\t\022\021\n\tuser_name\030\004 \001(\t\022\020\n\010user_pwd\030\005 \001(" +
      "\t\022\021\n\tuser_role\030\006 \001(\t\022\022\n\nuser_group\030\007 \001(\t" +
      "\022\023\n\013user_mobile\030\010 \001(\t\022\025\n\rsimcard_iccid\030\t" +
      " \001(\t\022\025\n\rmaster_number\030\n \001(\t\"R\n\013System_No" +
      "de\022\r\n\tUNIVERSAL\020\000\022\n\n\006MASTER\020\001\022\014\n\010TERMINA" +
      "L\020\002\022\n\n\006SERVER\020\003\022\016\n\nWEBBROWSER\020\004BX\n\035com.g" +
      "oldingmedia.goldingcloudB\013LogonProtos\252\002)",
      "com.goldingmedia.goldingcloud.LogonProto" +
      "sb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_goldingcloud_CLogon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_goldingcloud_CLogon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_goldingcloud_CLogon_descriptor,
        new java.lang.String[] { "SysObj", "DevId", "MasterId", "UserName", "UserPwd", "UserRole", "UserGroup", "UserMobile", "SimcardIccid", "MasterNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
