// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayMeta.proto

package com.goldingmedia.goldingcloud;

public final class PayMetaProtos {
  private PayMetaProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CPayMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:goldingcloud.CPayMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * false: free; true: pay
     * </pre>
     *
     * <code>bool Pay_type = 1;</code>
     */
    boolean getPayType();

    /**
     * <pre>
     * pay result:successful/failed
     * </pre>
     *
     * <code>bool pay_result = 2;</code>
     */
    boolean getPayResult();

    /**
     * <pre>
     * pay state:1-not pay,2-pay
     * </pre>
     *
     * <code>bool pay_state = 3;</code>
     */
    boolean getPayState();

    /**
     * <pre>
     * default:5 minute
     * </pre>
     *
     * <code>int32 pay_free_time = 4;</code>
     */
    int getPayFreeTime();

    /**
     * <pre>
     * pay value
     * </pre>
     *
     * <code>int32 pay_value = 5;</code>
     */
    int getPayValue();

    /**
     * <pre>
     * 1-yuan,2-jiao,3-fen
     * </pre>
     *
     * <code>int32 pay_unit = 6;</code>
     */
    int getPayUnit();

    /**
     * <pre>
     * click count
     * </pre>
     *
     * <code>int32 pay_counter = 7;</code>
     */
    int getPayCounter();

    /**
     * <pre>
     * weixin or the other
     * </pre>
     *
     * <code>string pay_interface = 8;</code>
     */
    java.lang.String getPayInterface();
    /**
     * <pre>
     * weixin or the other
     * </pre>
     *
     * <code>string pay_interface = 8;</code>
     */
    com.google.protobuf.ByteString
        getPayInterfaceBytes();

    /**
     * <pre>
     * 1-mobile,2-pc
     * </pre>
     *
     * <code>int32 pay_mode = 9;</code>
     */
    int getPayMode();

    /**
     * <pre>
     * yy-mm-dd hh:mm:ss,update time per pay
     * </pre>
     *
     * <code>string pay_time = 10;</code>
     */
    java.lang.String getPayTime();
    /**
     * <pre>
     * yy-mm-dd hh:mm:ss,update time per pay
     * </pre>
     *
     * <code>string pay_time = 10;</code>
     */
    com.google.protobuf.ByteString
        getPayTimeBytes();
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code goldingcloud.CPayMeta}
   */
  public  static final class CPayMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:goldingcloud.CPayMeta)
      CPayMetaOrBuilder {
    // Use CPayMeta.newBuilder() to construct.
    private CPayMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CPayMeta() {
      payType_ = false;
      payResult_ = false;
      payState_ = false;
      payFreeTime_ = 0;
      payValue_ = 0;
      payUnit_ = 0;
      payCounter_ = 0;
      payInterface_ = "";
      payMode_ = 0;
      payTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CPayMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              payType_ = input.readBool();
              break;
            }
            case 16: {

              payResult_ = input.readBool();
              break;
            }
            case 24: {

              payState_ = input.readBool();
              break;
            }
            case 32: {

              payFreeTime_ = input.readInt32();
              break;
            }
            case 40: {

              payValue_ = input.readInt32();
              break;
            }
            case 48: {

              payUnit_ = input.readInt32();
              break;
            }
            case 56: {

              payCounter_ = input.readInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              payInterface_ = s;
              break;
            }
            case 72: {

              payMode_ = input.readInt32();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              payTime_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.goldingmedia.goldingcloud.PayMetaProtos.internal_static_goldingcloud_CPayMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.goldingmedia.goldingcloud.PayMetaProtos.internal_static_goldingcloud_CPayMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.class, com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.Builder.class);
    }

    public static final int PAY_TYPE_FIELD_NUMBER = 1;
    private boolean payType_;
    /**
     * <pre>
     * false: free; true: pay
     * </pre>
     *
     * <code>bool Pay_type = 1;</code>
     */
    public boolean getPayType() {
      return payType_;
    }

    public static final int PAY_RESULT_FIELD_NUMBER = 2;
    private boolean payResult_;
    /**
     * <pre>
     * pay result:successful/failed
     * </pre>
     *
     * <code>bool pay_result = 2;</code>
     */
    public boolean getPayResult() {
      return payResult_;
    }

    public static final int PAY_STATE_FIELD_NUMBER = 3;
    private boolean payState_;
    /**
     * <pre>
     * pay state:1-not pay,2-pay
     * </pre>
     *
     * <code>bool pay_state = 3;</code>
     */
    public boolean getPayState() {
      return payState_;
    }

    public static final int PAY_FREE_TIME_FIELD_NUMBER = 4;
    private int payFreeTime_;
    /**
     * <pre>
     * default:5 minute
     * </pre>
     *
     * <code>int32 pay_free_time = 4;</code>
     */
    public int getPayFreeTime() {
      return payFreeTime_;
    }

    public static final int PAY_VALUE_FIELD_NUMBER = 5;
    private int payValue_;
    /**
     * <pre>
     * pay value
     * </pre>
     *
     * <code>int32 pay_value = 5;</code>
     */
    public int getPayValue() {
      return payValue_;
    }

    public static final int PAY_UNIT_FIELD_NUMBER = 6;
    private int payUnit_;
    /**
     * <pre>
     * 1-yuan,2-jiao,3-fen
     * </pre>
     *
     * <code>int32 pay_unit = 6;</code>
     */
    public int getPayUnit() {
      return payUnit_;
    }

    public static final int PAY_COUNTER_FIELD_NUMBER = 7;
    private int payCounter_;
    /**
     * <pre>
     * click count
     * </pre>
     *
     * <code>int32 pay_counter = 7;</code>
     */
    public int getPayCounter() {
      return payCounter_;
    }

    public static final int PAY_INTERFACE_FIELD_NUMBER = 8;
    private volatile java.lang.Object payInterface_;
    /**
     * <pre>
     * weixin or the other
     * </pre>
     *
     * <code>string pay_interface = 8;</code>
     */
    public java.lang.String getPayInterface() {
      java.lang.Object ref = payInterface_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payInterface_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * weixin or the other
     * </pre>
     *
     * <code>string pay_interface = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPayInterfaceBytes() {
      java.lang.Object ref = payInterface_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payInterface_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAY_MODE_FIELD_NUMBER = 9;
    private int payMode_;
    /**
     * <pre>
     * 1-mobile,2-pc
     * </pre>
     *
     * <code>int32 pay_mode = 9;</code>
     */
    public int getPayMode() {
      return payMode_;
    }

    public static final int PAY_TIME_FIELD_NUMBER = 10;
    private volatile java.lang.Object payTime_;
    /**
     * <pre>
     * yy-mm-dd hh:mm:ss,update time per pay
     * </pre>
     *
     * <code>string pay_time = 10;</code>
     */
    public java.lang.String getPayTime() {
      java.lang.Object ref = payTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * yy-mm-dd hh:mm:ss,update time per pay
     * </pre>
     *
     * <code>string pay_time = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPayTimeBytes() {
      java.lang.Object ref = payTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (payType_ != false) {
        output.writeBool(1, payType_);
      }
      if (payResult_ != false) {
        output.writeBool(2, payResult_);
      }
      if (payState_ != false) {
        output.writeBool(3, payState_);
      }
      if (payFreeTime_ != 0) {
        output.writeInt32(4, payFreeTime_);
      }
      if (payValue_ != 0) {
        output.writeInt32(5, payValue_);
      }
      if (payUnit_ != 0) {
        output.writeInt32(6, payUnit_);
      }
      if (payCounter_ != 0) {
        output.writeInt32(7, payCounter_);
      }
      if (!getPayInterfaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, payInterface_);
      }
      if (payMode_ != 0) {
        output.writeInt32(9, payMode_);
      }
      if (!getPayTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, payTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (payType_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, payType_);
      }
      if (payResult_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, payResult_);
      }
      if (payState_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, payState_);
      }
      if (payFreeTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, payFreeTime_);
      }
      if (payValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, payValue_);
      }
      if (payUnit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, payUnit_);
      }
      if (payCounter_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, payCounter_);
      }
      if (!getPayInterfaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, payInterface_);
      }
      if (payMode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, payMode_);
      }
      if (!getPayTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, payTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta)) {
        return super.equals(obj);
      }
      com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta other = (com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta) obj;

      boolean result = true;
      result = result && (getPayType()
          == other.getPayType());
      result = result && (getPayResult()
          == other.getPayResult());
      result = result && (getPayState()
          == other.getPayState());
      result = result && (getPayFreeTime()
          == other.getPayFreeTime());
      result = result && (getPayValue()
          == other.getPayValue());
      result = result && (getPayUnit()
          == other.getPayUnit());
      result = result && (getPayCounter()
          == other.getPayCounter());
      result = result && getPayInterface()
          .equals(other.getPayInterface());
      result = result && (getPayMode()
          == other.getPayMode());
      result = result && getPayTime()
          .equals(other.getPayTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPayType());
      hash = (37 * hash) + PAY_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPayResult());
      hash = (37 * hash) + PAY_STATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPayState());
      hash = (37 * hash) + PAY_FREE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getPayFreeTime();
      hash = (37 * hash) + PAY_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getPayValue();
      hash = (37 * hash) + PAY_UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getPayUnit();
      hash = (37 * hash) + PAY_COUNTER_FIELD_NUMBER;
      hash = (53 * hash) + getPayCounter();
      hash = (37 * hash) + PAY_INTERFACE_FIELD_NUMBER;
      hash = (53 * hash) + getPayInterface().hashCode();
      hash = (37 * hash) + PAY_MODE_FIELD_NUMBER;
      hash = (53 * hash) + getPayMode();
      hash = (37 * hash) + PAY_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getPayTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code goldingcloud.CPayMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:goldingcloud.CPayMeta)
        com.goldingmedia.goldingcloud.PayMetaProtos.CPayMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.goldingmedia.goldingcloud.PayMetaProtos.internal_static_goldingcloud_CPayMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.goldingmedia.goldingcloud.PayMetaProtos.internal_static_goldingcloud_CPayMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.class, com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.Builder.class);
      }

      // Construct using com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        payType_ = false;

        payResult_ = false;

        payState_ = false;

        payFreeTime_ = 0;

        payValue_ = 0;

        payUnit_ = 0;

        payCounter_ = 0;

        payInterface_ = "";

        payMode_ = 0;

        payTime_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.goldingmedia.goldingcloud.PayMetaProtos.internal_static_goldingcloud_CPayMeta_descriptor;
      }

      public com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta getDefaultInstanceForType() {
        return com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.getDefaultInstance();
      }

      public com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta build() {
        com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta buildPartial() {
        com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta result = new com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta(this);
        result.payType_ = payType_;
        result.payResult_ = payResult_;
        result.payState_ = payState_;
        result.payFreeTime_ = payFreeTime_;
        result.payValue_ = payValue_;
        result.payUnit_ = payUnit_;
        result.payCounter_ = payCounter_;
        result.payInterface_ = payInterface_;
        result.payMode_ = payMode_;
        result.payTime_ = payTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta) {
          return mergeFrom((com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta other) {
        if (other == com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.getDefaultInstance()) return this;
        if (other.getPayType() != false) {
          setPayType(other.getPayType());
        }
        if (other.getPayResult() != false) {
          setPayResult(other.getPayResult());
        }
        if (other.getPayState() != false) {
          setPayState(other.getPayState());
        }
        if (other.getPayFreeTime() != 0) {
          setPayFreeTime(other.getPayFreeTime());
        }
        if (other.getPayValue() != 0) {
          setPayValue(other.getPayValue());
        }
        if (other.getPayUnit() != 0) {
          setPayUnit(other.getPayUnit());
        }
        if (other.getPayCounter() != 0) {
          setPayCounter(other.getPayCounter());
        }
        if (!other.getPayInterface().isEmpty()) {
          payInterface_ = other.payInterface_;
          onChanged();
        }
        if (other.getPayMode() != 0) {
          setPayMode(other.getPayMode());
        }
        if (!other.getPayTime().isEmpty()) {
          payTime_ = other.payTime_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean payType_ ;
      /**
       * <pre>
       * false: free; true: pay
       * </pre>
       *
       * <code>bool Pay_type = 1;</code>
       */
      public boolean getPayType() {
        return payType_;
      }
      /**
       * <pre>
       * false: free; true: pay
       * </pre>
       *
       * <code>bool Pay_type = 1;</code>
       */
      public Builder setPayType(boolean value) {
        
        payType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * false: free; true: pay
       * </pre>
       *
       * <code>bool Pay_type = 1;</code>
       */
      public Builder clearPayType() {
        
        payType_ = false;
        onChanged();
        return this;
      }

      private boolean payResult_ ;
      /**
       * <pre>
       * pay result:successful/failed
       * </pre>
       *
       * <code>bool pay_result = 2;</code>
       */
      public boolean getPayResult() {
        return payResult_;
      }
      /**
       * <pre>
       * pay result:successful/failed
       * </pre>
       *
       * <code>bool pay_result = 2;</code>
       */
      public Builder setPayResult(boolean value) {
        
        payResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * pay result:successful/failed
       * </pre>
       *
       * <code>bool pay_result = 2;</code>
       */
      public Builder clearPayResult() {
        
        payResult_ = false;
        onChanged();
        return this;
      }

      private boolean payState_ ;
      /**
       * <pre>
       * pay state:1-not pay,2-pay
       * </pre>
       *
       * <code>bool pay_state = 3;</code>
       */
      public boolean getPayState() {
        return payState_;
      }
      /**
       * <pre>
       * pay state:1-not pay,2-pay
       * </pre>
       *
       * <code>bool pay_state = 3;</code>
       */
      public Builder setPayState(boolean value) {
        
        payState_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * pay state:1-not pay,2-pay
       * </pre>
       *
       * <code>bool pay_state = 3;</code>
       */
      public Builder clearPayState() {
        
        payState_ = false;
        onChanged();
        return this;
      }

      private int payFreeTime_ ;
      /**
       * <pre>
       * default:5 minute
       * </pre>
       *
       * <code>int32 pay_free_time = 4;</code>
       */
      public int getPayFreeTime() {
        return payFreeTime_;
      }
      /**
       * <pre>
       * default:5 minute
       * </pre>
       *
       * <code>int32 pay_free_time = 4;</code>
       */
      public Builder setPayFreeTime(int value) {
        
        payFreeTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * default:5 minute
       * </pre>
       *
       * <code>int32 pay_free_time = 4;</code>
       */
      public Builder clearPayFreeTime() {
        
        payFreeTime_ = 0;
        onChanged();
        return this;
      }

      private int payValue_ ;
      /**
       * <pre>
       * pay value
       * </pre>
       *
       * <code>int32 pay_value = 5;</code>
       */
      public int getPayValue() {
        return payValue_;
      }
      /**
       * <pre>
       * pay value
       * </pre>
       *
       * <code>int32 pay_value = 5;</code>
       */
      public Builder setPayValue(int value) {
        
        payValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * pay value
       * </pre>
       *
       * <code>int32 pay_value = 5;</code>
       */
      public Builder clearPayValue() {
        
        payValue_ = 0;
        onChanged();
        return this;
      }

      private int payUnit_ ;
      /**
       * <pre>
       * 1-yuan,2-jiao,3-fen
       * </pre>
       *
       * <code>int32 pay_unit = 6;</code>
       */
      public int getPayUnit() {
        return payUnit_;
      }
      /**
       * <pre>
       * 1-yuan,2-jiao,3-fen
       * </pre>
       *
       * <code>int32 pay_unit = 6;</code>
       */
      public Builder setPayUnit(int value) {
        
        payUnit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1-yuan,2-jiao,3-fen
       * </pre>
       *
       * <code>int32 pay_unit = 6;</code>
       */
      public Builder clearPayUnit() {
        
        payUnit_ = 0;
        onChanged();
        return this;
      }

      private int payCounter_ ;
      /**
       * <pre>
       * click count
       * </pre>
       *
       * <code>int32 pay_counter = 7;</code>
       */
      public int getPayCounter() {
        return payCounter_;
      }
      /**
       * <pre>
       * click count
       * </pre>
       *
       * <code>int32 pay_counter = 7;</code>
       */
      public Builder setPayCounter(int value) {
        
        payCounter_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * click count
       * </pre>
       *
       * <code>int32 pay_counter = 7;</code>
       */
      public Builder clearPayCounter() {
        
        payCounter_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object payInterface_ = "";
      /**
       * <pre>
       * weixin or the other
       * </pre>
       *
       * <code>string pay_interface = 8;</code>
       */
      public java.lang.String getPayInterface() {
        java.lang.Object ref = payInterface_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          payInterface_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * weixin or the other
       * </pre>
       *
       * <code>string pay_interface = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPayInterfaceBytes() {
        java.lang.Object ref = payInterface_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payInterface_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * weixin or the other
       * </pre>
       *
       * <code>string pay_interface = 8;</code>
       */
      public Builder setPayInterface(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payInterface_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * weixin or the other
       * </pre>
       *
       * <code>string pay_interface = 8;</code>
       */
      public Builder clearPayInterface() {
        
        payInterface_ = getDefaultInstance().getPayInterface();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * weixin or the other
       * </pre>
       *
       * <code>string pay_interface = 8;</code>
       */
      public Builder setPayInterfaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        payInterface_ = value;
        onChanged();
        return this;
      }

      private int payMode_ ;
      /**
       * <pre>
       * 1-mobile,2-pc
       * </pre>
       *
       * <code>int32 pay_mode = 9;</code>
       */
      public int getPayMode() {
        return payMode_;
      }
      /**
       * <pre>
       * 1-mobile,2-pc
       * </pre>
       *
       * <code>int32 pay_mode = 9;</code>
       */
      public Builder setPayMode(int value) {
        
        payMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1-mobile,2-pc
       * </pre>
       *
       * <code>int32 pay_mode = 9;</code>
       */
      public Builder clearPayMode() {
        
        payMode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object payTime_ = "";
      /**
       * <pre>
       * yy-mm-dd hh:mm:ss,update time per pay
       * </pre>
       *
       * <code>string pay_time = 10;</code>
       */
      public java.lang.String getPayTime() {
        java.lang.Object ref = payTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          payTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * yy-mm-dd hh:mm:ss,update time per pay
       * </pre>
       *
       * <code>string pay_time = 10;</code>
       */
      public com.google.protobuf.ByteString
          getPayTimeBytes() {
        java.lang.Object ref = payTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * yy-mm-dd hh:mm:ss,update time per pay
       * </pre>
       *
       * <code>string pay_time = 10;</code>
       */
      public Builder setPayTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * yy-mm-dd hh:mm:ss,update time per pay
       * </pre>
       *
       * <code>string pay_time = 10;</code>
       */
      public Builder clearPayTime() {
        
        payTime_ = getDefaultInstance().getPayTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * yy-mm-dd hh:mm:ss,update time per pay
       * </pre>
       *
       * <code>string pay_time = 10;</code>
       */
      public Builder setPayTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        payTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:goldingcloud.CPayMeta)
    }

    // @@protoc_insertion_point(class_scope:goldingcloud.CPayMeta)
    private static final com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta();
    }

    public static com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CPayMeta>
        PARSER = new com.google.protobuf.AbstractParser<CPayMeta>() {
      public CPayMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CPayMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CPayMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CPayMeta> getParserForType() {
      return PARSER;
    }

    public com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_goldingcloud_CPayMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_goldingcloud_CPayMeta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPayMeta.proto\022\014goldingcloud\"\317\001\n\010CPayMe" +
      "ta\022\020\n\010Pay_type\030\001 \001(\010\022\022\n\npay_result\030\002 \001(\010" +
      "\022\021\n\tpay_state\030\003 \001(\010\022\025\n\rpay_free_time\030\004 \001" +
      "(\005\022\021\n\tpay_value\030\005 \001(\005\022\020\n\010pay_unit\030\006 \001(\005\022" +
      "\023\n\013pay_counter\030\007 \001(\005\022\025\n\rpay_interface\030\010 " +
      "\001(\t\022\020\n\010pay_mode\030\t \001(\005\022\020\n\010pay_time\030\n \001(\tB" +
      "\\\n\035com.goldingmedia.goldingcloudB\rPayMet" +
      "aProtos\252\002+com.goldingmedia.goldingcloud." +
      "PayMetaProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_goldingcloud_CPayMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_goldingcloud_CPayMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_goldingcloud_CPayMeta_descriptor,
        new java.lang.String[] { "PayType", "PayResult", "PayState", "PayFreeTime", "PayValue", "PayUnit", "PayCounter", "PayInterface", "PayMode", "PayTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
