// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systemConfig.proto

package com.goldingmedia.goldingcloud;

public final class SystemConfigProtos {
  private SystemConfigProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CConfigMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:goldingcloud.CConfigMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sdcard_mount_point = 1;</code>
     */
    java.lang.String getSdcardMountPoint();
    /**
     * <code>string sdcard_mount_point = 1;</code>
     */
    com.google.protobuf.ByteString
        getSdcardMountPointBytes();

    /**
     * <code>string system_date = 2;</code>
     */
    java.lang.String getSystemDate();
    /**
     * <code>string system_date = 2;</code>
     */
    com.google.protobuf.ByteString
        getSystemDateBytes();
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code goldingcloud.CConfigMeta}
   */
  public  static final class CConfigMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:goldingcloud.CConfigMeta)
      CConfigMetaOrBuilder {
    // Use CConfigMeta.newBuilder() to construct.
    private CConfigMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CConfigMeta() {
      sdcardMountPoint_ = "";
      systemDate_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CConfigMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sdcardMountPoint_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              systemDate_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.goldingmedia.goldingcloud.SystemConfigProtos.internal_static_goldingcloud_CConfigMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.goldingmedia.goldingcloud.SystemConfigProtos.internal_static_goldingcloud_CConfigMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.class, com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.Builder.class);
    }

    public static final int SDCARD_MOUNT_POINT_FIELD_NUMBER = 1;
    private volatile java.lang.Object sdcardMountPoint_;
    /**
     * <code>string sdcard_mount_point = 1;</code>
     */
    public java.lang.String getSdcardMountPoint() {
      java.lang.Object ref = sdcardMountPoint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sdcardMountPoint_ = s;
        return s;
      }
    }
    /**
     * <code>string sdcard_mount_point = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSdcardMountPointBytes() {
      java.lang.Object ref = sdcardMountPoint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdcardMountPoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYSTEM_DATE_FIELD_NUMBER = 2;
    private volatile java.lang.Object systemDate_;
    /**
     * <code>string system_date = 2;</code>
     */
    public java.lang.String getSystemDate() {
      java.lang.Object ref = systemDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        systemDate_ = s;
        return s;
      }
    }
    /**
     * <code>string system_date = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSystemDateBytes() {
      java.lang.Object ref = systemDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSdcardMountPointBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sdcardMountPoint_);
      }
      if (!getSystemDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, systemDate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSdcardMountPointBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sdcardMountPoint_);
      }
      if (!getSystemDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, systemDate_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta)) {
        return super.equals(obj);
      }
      com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta other = (com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta) obj;

      boolean result = true;
      result = result && getSdcardMountPoint()
          .equals(other.getSdcardMountPoint());
      result = result && getSystemDate()
          .equals(other.getSystemDate());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SDCARD_MOUNT_POINT_FIELD_NUMBER;
      hash = (53 * hash) + getSdcardMountPoint().hashCode();
      hash = (37 * hash) + SYSTEM_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getSystemDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code goldingcloud.CConfigMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:goldingcloud.CConfigMeta)
        com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.goldingmedia.goldingcloud.SystemConfigProtos.internal_static_goldingcloud_CConfigMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.goldingmedia.goldingcloud.SystemConfigProtos.internal_static_goldingcloud_CConfigMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.class, com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.Builder.class);
      }

      // Construct using com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sdcardMountPoint_ = "";

        systemDate_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.goldingmedia.goldingcloud.SystemConfigProtos.internal_static_goldingcloud_CConfigMeta_descriptor;
      }

      public com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta getDefaultInstanceForType() {
        return com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.getDefaultInstance();
      }

      public com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta build() {
        com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta buildPartial() {
        com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta result = new com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta(this);
        result.sdcardMountPoint_ = sdcardMountPoint_;
        result.systemDate_ = systemDate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta) {
          return mergeFrom((com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta other) {
        if (other == com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.getDefaultInstance()) return this;
        if (!other.getSdcardMountPoint().isEmpty()) {
          sdcardMountPoint_ = other.sdcardMountPoint_;
          onChanged();
        }
        if (!other.getSystemDate().isEmpty()) {
          systemDate_ = other.systemDate_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sdcardMountPoint_ = "";
      /**
       * <code>string sdcard_mount_point = 1;</code>
       */
      public java.lang.String getSdcardMountPoint() {
        java.lang.Object ref = sdcardMountPoint_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sdcardMountPoint_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sdcard_mount_point = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSdcardMountPointBytes() {
        java.lang.Object ref = sdcardMountPoint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdcardMountPoint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sdcard_mount_point = 1;</code>
       */
      public Builder setSdcardMountPoint(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sdcardMountPoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sdcard_mount_point = 1;</code>
       */
      public Builder clearSdcardMountPoint() {
        
        sdcardMountPoint_ = getDefaultInstance().getSdcardMountPoint();
        onChanged();
        return this;
      }
      /**
       * <code>string sdcard_mount_point = 1;</code>
       */
      public Builder setSdcardMountPointBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sdcardMountPoint_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object systemDate_ = "";
      /**
       * <code>string system_date = 2;</code>
       */
      public java.lang.String getSystemDate() {
        java.lang.Object ref = systemDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          systemDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string system_date = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSystemDateBytes() {
        java.lang.Object ref = systemDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          systemDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string system_date = 2;</code>
       */
      public Builder setSystemDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        systemDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string system_date = 2;</code>
       */
      public Builder clearSystemDate() {
        
        systemDate_ = getDefaultInstance().getSystemDate();
        onChanged();
        return this;
      }
      /**
       * <code>string system_date = 2;</code>
       */
      public Builder setSystemDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        systemDate_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:goldingcloud.CConfigMeta)
    }

    // @@protoc_insertion_point(class_scope:goldingcloud.CConfigMeta)
    private static final com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta();
    }

    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CConfigMeta>
        PARSER = new com.google.protobuf.AbstractParser<CConfigMeta>() {
      public CConfigMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CConfigMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CConfigMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CConfigMeta> getParserForType() {
      return PARSER;
    }

    public com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CSystemConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:goldingcloud.CSystemConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.goldingcloud.CConfigMeta config = 1;</code>
     */
    boolean hasConfig();
    /**
     * <code>.goldingcloud.CConfigMeta config = 1;</code>
     */
    com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta getConfig();
    /**
     * <code>.goldingcloud.CConfigMeta config = 1;</code>
     */
    com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMetaOrBuilder getConfigOrBuilder();
  }
  /**
   * Protobuf type {@code goldingcloud.CSystemConfig}
   */
  public  static final class CSystemConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:goldingcloud.CSystemConfig)
      CSystemConfigOrBuilder {
    // Use CSystemConfig.newBuilder() to construct.
    private CSystemConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSystemConfig() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CSystemConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.Builder subBuilder = null;
              if (config_ != null) {
                subBuilder = config_.toBuilder();
              }
              config_ = input.readMessage(com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(config_);
                config_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.goldingmedia.goldingcloud.SystemConfigProtos.internal_static_goldingcloud_CSystemConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.goldingmedia.goldingcloud.SystemConfigProtos.internal_static_goldingcloud_CSystemConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig.class, com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig.Builder.class);
    }

    public static final int CONFIG_FIELD_NUMBER = 1;
    private com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta config_;
    /**
     * <code>.goldingcloud.CConfigMeta config = 1;</code>
     */
    public boolean hasConfig() {
      return config_ != null;
    }
    /**
     * <code>.goldingcloud.CConfigMeta config = 1;</code>
     */
    public com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta getConfig() {
      return config_ == null ? com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.getDefaultInstance() : config_;
    }
    /**
     * <code>.goldingcloud.CConfigMeta config = 1;</code>
     */
    public com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMetaOrBuilder getConfigOrBuilder() {
      return getConfig();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (config_ != null) {
        output.writeMessage(1, getConfig());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (config_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getConfig());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig)) {
        return super.equals(obj);
      }
      com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig other = (com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig) obj;

      boolean result = true;
      result = result && (hasConfig() == other.hasConfig());
      if (hasConfig()) {
        result = result && getConfig()
            .equals(other.getConfig());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConfig()) {
        hash = (37 * hash) + CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getConfig().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code goldingcloud.CSystemConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:goldingcloud.CSystemConfig)
        com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.goldingmedia.goldingcloud.SystemConfigProtos.internal_static_goldingcloud_CSystemConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.goldingmedia.goldingcloud.SystemConfigProtos.internal_static_goldingcloud_CSystemConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig.class, com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig.Builder.class);
      }

      // Construct using com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (configBuilder_ == null) {
          config_ = null;
        } else {
          config_ = null;
          configBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.goldingmedia.goldingcloud.SystemConfigProtos.internal_static_goldingcloud_CSystemConfig_descriptor;
      }

      public com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig getDefaultInstanceForType() {
        return com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig.getDefaultInstance();
      }

      public com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig build() {
        com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig buildPartial() {
        com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig result = new com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig(this);
        if (configBuilder_ == null) {
          result.config_ = config_;
        } else {
          result.config_ = configBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig) {
          return mergeFrom((com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig other) {
        if (other == com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig.getDefaultInstance()) return this;
        if (other.hasConfig()) {
          mergeConfig(other.getConfig());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta config_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta, com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.Builder, com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMetaOrBuilder> configBuilder_;
      /**
       * <code>.goldingcloud.CConfigMeta config = 1;</code>
       */
      public boolean hasConfig() {
        return configBuilder_ != null || config_ != null;
      }
      /**
       * <code>.goldingcloud.CConfigMeta config = 1;</code>
       */
      public com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta getConfig() {
        if (configBuilder_ == null) {
          return config_ == null ? com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.getDefaultInstance() : config_;
        } else {
          return configBuilder_.getMessage();
        }
      }
      /**
       * <code>.goldingcloud.CConfigMeta config = 1;</code>
       */
      public Builder setConfig(com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta value) {
        if (configBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          config_ = value;
          onChanged();
        } else {
          configBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CConfigMeta config = 1;</code>
       */
      public Builder setConfig(
          com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.Builder builderForValue) {
        if (configBuilder_ == null) {
          config_ = builderForValue.build();
          onChanged();
        } else {
          configBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CConfigMeta config = 1;</code>
       */
      public Builder mergeConfig(com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta value) {
        if (configBuilder_ == null) {
          if (config_ != null) {
            config_ =
              com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.newBuilder(config_).mergeFrom(value).buildPartial();
          } else {
            config_ = value;
          }
          onChanged();
        } else {
          configBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CConfigMeta config = 1;</code>
       */
      public Builder clearConfig() {
        if (configBuilder_ == null) {
          config_ = null;
          onChanged();
        } else {
          config_ = null;
          configBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CConfigMeta config = 1;</code>
       */
      public com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.Builder getConfigBuilder() {
        
        onChanged();
        return getConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>.goldingcloud.CConfigMeta config = 1;</code>
       */
      public com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMetaOrBuilder getConfigOrBuilder() {
        if (configBuilder_ != null) {
          return configBuilder_.getMessageOrBuilder();
        } else {
          return config_ == null ?
              com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.getDefaultInstance() : config_;
        }
      }
      /**
       * <code>.goldingcloud.CConfigMeta config = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta, com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.Builder, com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMetaOrBuilder> 
          getConfigFieldBuilder() {
        if (configBuilder_ == null) {
          configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta, com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMeta.Builder, com.goldingmedia.goldingcloud.SystemConfigProtos.CConfigMetaOrBuilder>(
                  getConfig(),
                  getParentForChildren(),
                  isClean());
          config_ = null;
        }
        return configBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:goldingcloud.CSystemConfig)
    }

    // @@protoc_insertion_point(class_scope:goldingcloud.CSystemConfig)
    private static final com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig();
    }

    public static com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CSystemConfig>
        PARSER = new com.google.protobuf.AbstractParser<CSystemConfig>() {
      public CSystemConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CSystemConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSystemConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSystemConfig> getParserForType() {
      return PARSER;
    }

    public com.goldingmedia.goldingcloud.SystemConfigProtos.CSystemConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_goldingcloud_CConfigMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_goldingcloud_CConfigMeta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_goldingcloud_CSystemConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_goldingcloud_CSystemConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022systemConfig.proto\022\014goldingcloud\">\n\013CC" +
      "onfigMeta\022\032\n\022sdcard_mount_point\030\001 \001(\t\022\023\n" +
      "\013system_date\030\002 \001(\t\":\n\rCSystemConfig\022)\n\006c" +
      "onfig\030\001 \001(\0132\031.goldingcloud.CConfigMetaBf" +
      "\n\035com.goldingmedia.goldingcloudB\022SystemC" +
      "onfigProtos\252\0020com.goldingmedia.goldingcl" +
      "oud.SystemConfigProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_goldingcloud_CConfigMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_goldingcloud_CConfigMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_goldingcloud_CConfigMeta_descriptor,
        new java.lang.String[] { "SdcardMountPoint", "SystemDate", });
    internal_static_goldingcloud_CSystemConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_goldingcloud_CSystemConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_goldingcloud_CSystemConfig_descriptor,
        new java.lang.String[] { "Config", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
