// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TruckMedia.proto

package com.goldingmedia.goldingcloud;

public final class TruckMediaProtos {
  private TruckMediaProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CTruckMediaNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:goldingcloud.CTruckMediaNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 category_id = 1;</code>
     */
    int getCategoryId();

    /**
     * <code>int32 category_sub_id = 2;</code>
     */
    int getCategorySubId();

    /**
     * <pre>
     * truck media info,apk or ts stream file
     * </pre>
     *
     * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
     */
    boolean hasMediaInfo();
    /**
     * <pre>
     * truck media info,apk or ts stream file
     * </pre>
     *
     * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
     */
    com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta getMediaInfo();
    /**
     * <pre>
     * truck media info,apk or ts stream file
     * </pre>
     *
     * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
     */
    com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMetaOrBuilder getMediaInfoOrBuilder();

    /**
     * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
     */
    boolean hasPlayInfo();
    /**
     * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
     */
    com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta getPlayInfo();
    /**
     * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
     */
    com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMetaOrBuilder getPlayInfoOrBuilder();

    /**
     * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
     */
    boolean hasPayInfo();
    /**
     * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
     */
    com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta getPayInfo();
    /**
     * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
     */
    com.goldingmedia.goldingcloud.PayMetaProtos.CPayMetaOrBuilder getPayInfoOrBuilder();
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code goldingcloud.CTruckMediaNode}
   */
  public  static final class CTruckMediaNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:goldingcloud.CTruckMediaNode)
      CTruckMediaNodeOrBuilder {
    // Use CTruckMediaNode.newBuilder() to construct.
    private CTruckMediaNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CTruckMediaNode() {
      categoryId_ = 0;
      categorySubId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CTruckMediaNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              categoryId_ = input.readInt32();
              break;
            }
            case 16: {

              categorySubId_ = input.readInt32();
              break;
            }
            case 26: {
              com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta.Builder subBuilder = null;
              if (mediaInfo_ != null) {
                subBuilder = mediaInfo_.toBuilder();
              }
              mediaInfo_ = input.readMessage(com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mediaInfo_);
                mediaInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta.Builder subBuilder = null;
              if (playInfo_ != null) {
                subBuilder = playInfo_.toBuilder();
              }
              playInfo_ = input.readMessage(com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(playInfo_);
                playInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.Builder subBuilder = null;
              if (payInfo_ != null) {
                subBuilder = payInfo_.toBuilder();
              }
              payInfo_ = input.readMessage(com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(payInfo_);
                payInfo_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.goldingmedia.goldingcloud.TruckMediaProtos.internal_static_goldingcloud_CTruckMediaNode_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.goldingmedia.goldingcloud.TruckMediaProtos.internal_static_goldingcloud_CTruckMediaNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode.class, com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode.Builder.class);
    }

    public static final int CATEGORY_ID_FIELD_NUMBER = 1;
    private int categoryId_;
    /**
     * <code>int32 category_id = 1;</code>
     */
    public int getCategoryId() {
      return categoryId_;
    }

    public static final int CATEGORY_SUB_ID_FIELD_NUMBER = 2;
    private int categorySubId_;
    /**
     * <code>int32 category_sub_id = 2;</code>
     */
    public int getCategorySubId() {
      return categorySubId_;
    }

    public static final int MEDIAINFO_FIELD_NUMBER = 3;
    private com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta mediaInfo_;
    /**
     * <pre>
     * truck media info,apk or ts stream file
     * </pre>
     *
     * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
     */
    public boolean hasMediaInfo() {
      return mediaInfo_ != null;
    }
    /**
     * <pre>
     * truck media info,apk or ts stream file
     * </pre>
     *
     * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
     */
    public com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta getMediaInfo() {
      return mediaInfo_ == null ? com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta.getDefaultInstance() : mediaInfo_;
    }
    /**
     * <pre>
     * truck media info,apk or ts stream file
     * </pre>
     *
     * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
     */
    public com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMetaOrBuilder getMediaInfoOrBuilder() {
      return getMediaInfo();
    }

    public static final int PLAYINFO_FIELD_NUMBER = 4;
    private com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta playInfo_;
    /**
     * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
     */
    public boolean hasPlayInfo() {
      return playInfo_ != null;
    }
    /**
     * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
     */
    public com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta getPlayInfo() {
      return playInfo_ == null ? com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta.getDefaultInstance() : playInfo_;
    }
    /**
     * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
     */
    public com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMetaOrBuilder getPlayInfoOrBuilder() {
      return getPlayInfo();
    }

    public static final int PAYINFO_FIELD_NUMBER = 5;
    private com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta payInfo_;
    /**
     * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
     */
    public boolean hasPayInfo() {
      return payInfo_ != null;
    }
    /**
     * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
     */
    public com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta getPayInfo() {
      return payInfo_ == null ? com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.getDefaultInstance() : payInfo_;
    }
    /**
     * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
     */
    public com.goldingmedia.goldingcloud.PayMetaProtos.CPayMetaOrBuilder getPayInfoOrBuilder() {
      return getPayInfo();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (categoryId_ != 0) {
        output.writeInt32(1, categoryId_);
      }
      if (categorySubId_ != 0) {
        output.writeInt32(2, categorySubId_);
      }
      if (mediaInfo_ != null) {
        output.writeMessage(3, getMediaInfo());
      }
      if (playInfo_ != null) {
        output.writeMessage(4, getPlayInfo());
      }
      if (payInfo_ != null) {
        output.writeMessage(5, getPayInfo());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (categoryId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, categoryId_);
      }
      if (categorySubId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, categorySubId_);
      }
      if (mediaInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMediaInfo());
      }
      if (playInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPlayInfo());
      }
      if (payInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPayInfo());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode)) {
        return super.equals(obj);
      }
      com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode other = (com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode) obj;

      boolean result = true;
      result = result && (getCategoryId()
          == other.getCategoryId());
      result = result && (getCategorySubId()
          == other.getCategorySubId());
      result = result && (hasMediaInfo() == other.hasMediaInfo());
      if (hasMediaInfo()) {
        result = result && getMediaInfo()
            .equals(other.getMediaInfo());
      }
      result = result && (hasPlayInfo() == other.hasPlayInfo());
      if (hasPlayInfo()) {
        result = result && getPlayInfo()
            .equals(other.getPlayInfo());
      }
      result = result && (hasPayInfo() == other.hasPayInfo());
      if (hasPayInfo()) {
        result = result && getPayInfo()
            .equals(other.getPayInfo());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CATEGORY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCategoryId();
      hash = (37 * hash) + CATEGORY_SUB_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCategorySubId();
      if (hasMediaInfo()) {
        hash = (37 * hash) + MEDIAINFO_FIELD_NUMBER;
        hash = (53 * hash) + getMediaInfo().hashCode();
      }
      if (hasPlayInfo()) {
        hash = (37 * hash) + PLAYINFO_FIELD_NUMBER;
        hash = (53 * hash) + getPlayInfo().hashCode();
      }
      if (hasPayInfo()) {
        hash = (37 * hash) + PAYINFO_FIELD_NUMBER;
        hash = (53 * hash) + getPayInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code goldingcloud.CTruckMediaNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:goldingcloud.CTruckMediaNode)
        com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.goldingmedia.goldingcloud.TruckMediaProtos.internal_static_goldingcloud_CTruckMediaNode_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.goldingmedia.goldingcloud.TruckMediaProtos.internal_static_goldingcloud_CTruckMediaNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode.class, com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode.Builder.class);
      }

      // Construct using com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        categoryId_ = 0;

        categorySubId_ = 0;

        if (mediaInfoBuilder_ == null) {
          mediaInfo_ = null;
        } else {
          mediaInfo_ = null;
          mediaInfoBuilder_ = null;
        }
        if (playInfoBuilder_ == null) {
          playInfo_ = null;
        } else {
          playInfo_ = null;
          playInfoBuilder_ = null;
        }
        if (payInfoBuilder_ == null) {
          payInfo_ = null;
        } else {
          payInfo_ = null;
          payInfoBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.goldingmedia.goldingcloud.TruckMediaProtos.internal_static_goldingcloud_CTruckMediaNode_descriptor;
      }

      public com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode getDefaultInstanceForType() {
        return com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode.getDefaultInstance();
      }

      public com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode build() {
        com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode buildPartial() {
        com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode result = new com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode(this);
        result.categoryId_ = categoryId_;
        result.categorySubId_ = categorySubId_;
        if (mediaInfoBuilder_ == null) {
          result.mediaInfo_ = mediaInfo_;
        } else {
          result.mediaInfo_ = mediaInfoBuilder_.build();
        }
        if (playInfoBuilder_ == null) {
          result.playInfo_ = playInfo_;
        } else {
          result.playInfo_ = playInfoBuilder_.build();
        }
        if (payInfoBuilder_ == null) {
          result.payInfo_ = payInfo_;
        } else {
          result.payInfo_ = payInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode) {
          return mergeFrom((com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode other) {
        if (other == com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode.getDefaultInstance()) return this;
        if (other.getCategoryId() != 0) {
          setCategoryId(other.getCategoryId());
        }
        if (other.getCategorySubId() != 0) {
          setCategorySubId(other.getCategorySubId());
        }
        if (other.hasMediaInfo()) {
          mergeMediaInfo(other.getMediaInfo());
        }
        if (other.hasPlayInfo()) {
          mergePlayInfo(other.getPlayInfo());
        }
        if (other.hasPayInfo()) {
          mergePayInfo(other.getPayInfo());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int categoryId_ ;
      /**
       * <code>int32 category_id = 1;</code>
       */
      public int getCategoryId() {
        return categoryId_;
      }
      /**
       * <code>int32 category_id = 1;</code>
       */
      public Builder setCategoryId(int value) {
        
        categoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 category_id = 1;</code>
       */
      public Builder clearCategoryId() {
        
        categoryId_ = 0;
        onChanged();
        return this;
      }

      private int categorySubId_ ;
      /**
       * <code>int32 category_sub_id = 2;</code>
       */
      public int getCategorySubId() {
        return categorySubId_;
      }
      /**
       * <code>int32 category_sub_id = 2;</code>
       */
      public Builder setCategorySubId(int value) {
        
        categorySubId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 category_sub_id = 2;</code>
       */
      public Builder clearCategorySubId() {
        
        categorySubId_ = 0;
        onChanged();
        return this;
      }

      private com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta mediaInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta, com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta.Builder, com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMetaOrBuilder> mediaInfoBuilder_;
      /**
       * <pre>
       * truck media info,apk or ts stream file
       * </pre>
       *
       * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
       */
      public boolean hasMediaInfo() {
        return mediaInfoBuilder_ != null || mediaInfo_ != null;
      }
      /**
       * <pre>
       * truck media info,apk or ts stream file
       * </pre>
       *
       * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
       */
      public com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta getMediaInfo() {
        if (mediaInfoBuilder_ == null) {
          return mediaInfo_ == null ? com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta.getDefaultInstance() : mediaInfo_;
        } else {
          return mediaInfoBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * truck media info,apk or ts stream file
       * </pre>
       *
       * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
       */
      public Builder setMediaInfo(com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta value) {
        if (mediaInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mediaInfo_ = value;
          onChanged();
        } else {
          mediaInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * truck media info,apk or ts stream file
       * </pre>
       *
       * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
       */
      public Builder setMediaInfo(
          com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta.Builder builderForValue) {
        if (mediaInfoBuilder_ == null) {
          mediaInfo_ = builderForValue.build();
          onChanged();
        } else {
          mediaInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * truck media info,apk or ts stream file
       * </pre>
       *
       * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
       */
      public Builder mergeMediaInfo(com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta value) {
        if (mediaInfoBuilder_ == null) {
          if (mediaInfo_ != null) {
            mediaInfo_ =
              com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta.newBuilder(mediaInfo_).mergeFrom(value).buildPartial();
          } else {
            mediaInfo_ = value;
          }
          onChanged();
        } else {
          mediaInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * truck media info,apk or ts stream file
       * </pre>
       *
       * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
       */
      public Builder clearMediaInfo() {
        if (mediaInfoBuilder_ == null) {
          mediaInfo_ = null;
          onChanged();
        } else {
          mediaInfo_ = null;
          mediaInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * truck media info,apk or ts stream file
       * </pre>
       *
       * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
       */
      public com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta.Builder getMediaInfoBuilder() {
        
        onChanged();
        return getMediaInfoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * truck media info,apk or ts stream file
       * </pre>
       *
       * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
       */
      public com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMetaOrBuilder getMediaInfoOrBuilder() {
        if (mediaInfoBuilder_ != null) {
          return mediaInfoBuilder_.getMessageOrBuilder();
        } else {
          return mediaInfo_ == null ?
              com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta.getDefaultInstance() : mediaInfo_;
        }
      }
      /**
       * <pre>
       * truck media info,apk or ts stream file
       * </pre>
       *
       * <code>.goldingcloud.CMediaMeta mediaInfo = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta, com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta.Builder, com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMetaOrBuilder> 
          getMediaInfoFieldBuilder() {
        if (mediaInfoBuilder_ == null) {
          mediaInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta, com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMeta.Builder, com.goldingmedia.goldingcloud.MediaMetaProtos.CMediaMetaOrBuilder>(
                  getMediaInfo(),
                  getParentForChildren(),
                  isClean());
          mediaInfo_ = null;
        }
        return mediaInfoBuilder_;
      }

      private com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta playInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta, com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta.Builder, com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMetaOrBuilder> playInfoBuilder_;
      /**
       * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
       */
      public boolean hasPlayInfo() {
        return playInfoBuilder_ != null || playInfo_ != null;
      }
      /**
       * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
       */
      public com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta getPlayInfo() {
        if (playInfoBuilder_ == null) {
          return playInfo_ == null ? com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta.getDefaultInstance() : playInfo_;
        } else {
          return playInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
       */
      public Builder setPlayInfo(com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta value) {
        if (playInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playInfo_ = value;
          onChanged();
        } else {
          playInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
       */
      public Builder setPlayInfo(
          com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta.Builder builderForValue) {
        if (playInfoBuilder_ == null) {
          playInfo_ = builderForValue.build();
          onChanged();
        } else {
          playInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
       */
      public Builder mergePlayInfo(com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta value) {
        if (playInfoBuilder_ == null) {
          if (playInfo_ != null) {
            playInfo_ =
              com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta.newBuilder(playInfo_).mergeFrom(value).buildPartial();
          } else {
            playInfo_ = value;
          }
          onChanged();
        } else {
          playInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
       */
      public Builder clearPlayInfo() {
        if (playInfoBuilder_ == null) {
          playInfo_ = null;
          onChanged();
        } else {
          playInfo_ = null;
          playInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
       */
      public com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta.Builder getPlayInfoBuilder() {
        
        onChanged();
        return getPlayInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
       */
      public com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMetaOrBuilder getPlayInfoOrBuilder() {
        if (playInfoBuilder_ != null) {
          return playInfoBuilder_.getMessageOrBuilder();
        } else {
          return playInfo_ == null ?
              com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta.getDefaultInstance() : playInfo_;
        }
      }
      /**
       * <code>.goldingcloud.CPlayerMeta playInfo = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta, com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta.Builder, com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMetaOrBuilder> 
          getPlayInfoFieldBuilder() {
        if (playInfoBuilder_ == null) {
          playInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta, com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMeta.Builder, com.goldingmedia.goldingcloud.PlayerMetaProtos.CPlayerMetaOrBuilder>(
                  getPlayInfo(),
                  getParentForChildren(),
                  isClean());
          playInfo_ = null;
        }
        return playInfoBuilder_;
      }

      private com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta payInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta, com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.Builder, com.goldingmedia.goldingcloud.PayMetaProtos.CPayMetaOrBuilder> payInfoBuilder_;
      /**
       * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
       */
      public boolean hasPayInfo() {
        return payInfoBuilder_ != null || payInfo_ != null;
      }
      /**
       * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
       */
      public com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta getPayInfo() {
        if (payInfoBuilder_ == null) {
          return payInfo_ == null ? com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.getDefaultInstance() : payInfo_;
        } else {
          return payInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
       */
      public Builder setPayInfo(com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta value) {
        if (payInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payInfo_ = value;
          onChanged();
        } else {
          payInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
       */
      public Builder setPayInfo(
          com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.Builder builderForValue) {
        if (payInfoBuilder_ == null) {
          payInfo_ = builderForValue.build();
          onChanged();
        } else {
          payInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
       */
      public Builder mergePayInfo(com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta value) {
        if (payInfoBuilder_ == null) {
          if (payInfo_ != null) {
            payInfo_ =
              com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.newBuilder(payInfo_).mergeFrom(value).buildPartial();
          } else {
            payInfo_ = value;
          }
          onChanged();
        } else {
          payInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
       */
      public Builder clearPayInfo() {
        if (payInfoBuilder_ == null) {
          payInfo_ = null;
          onChanged();
        } else {
          payInfo_ = null;
          payInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
       */
      public com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.Builder getPayInfoBuilder() {
        
        onChanged();
        return getPayInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
       */
      public com.goldingmedia.goldingcloud.PayMetaProtos.CPayMetaOrBuilder getPayInfoOrBuilder() {
        if (payInfoBuilder_ != null) {
          return payInfoBuilder_.getMessageOrBuilder();
        } else {
          return payInfo_ == null ?
              com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.getDefaultInstance() : payInfo_;
        }
      }
      /**
       * <code>.goldingcloud.CPayMeta payInfo = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta, com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.Builder, com.goldingmedia.goldingcloud.PayMetaProtos.CPayMetaOrBuilder> 
          getPayInfoFieldBuilder() {
        if (payInfoBuilder_ == null) {
          payInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta, com.goldingmedia.goldingcloud.PayMetaProtos.CPayMeta.Builder, com.goldingmedia.goldingcloud.PayMetaProtos.CPayMetaOrBuilder>(
                  getPayInfo(),
                  getParentForChildren(),
                  isClean());
          payInfo_ = null;
        }
        return payInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:goldingcloud.CTruckMediaNode)
    }

    // @@protoc_insertion_point(class_scope:goldingcloud.CTruckMediaNode)
    private static final com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode();
    }

    public static com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CTruckMediaNode>
        PARSER = new com.google.protobuf.AbstractParser<CTruckMediaNode>() {
      public CTruckMediaNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CTruckMediaNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CTruckMediaNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CTruckMediaNode> getParserForType() {
      return PARSER;
    }

    public com.goldingmedia.goldingcloud.TruckMediaProtos.CTruckMediaNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_goldingcloud_CTruckMediaNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_goldingcloud_CTruckMediaNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TruckMedia.proto\022\014goldingcloud\032\rPayMet" +
      "a.proto\032\020PlayerMeta.proto\032\017MediaMeta.pro" +
      "to\"\302\001\n\017CTruckMediaNode\022\023\n\013category_id\030\001 " +
      "\001(\005\022\027\n\017category_sub_id\030\002 \001(\005\022+\n\tmediaInf" +
      "o\030\003 \001(\0132\030.goldingcloud.CMediaMeta\022+\n\010pla" +
      "yInfo\030\004 \001(\0132\031.goldingcloud.CPlayerMeta\022\'" +
      "\n\007payInfo\030\005 \001(\0132\026.goldingcloud.CPayMetaB" +
      "b\n\035com.goldingmedia.goldingcloudB\020TruckM" +
      "ediaProtos\252\002.com.goldingmedia.goldingclo" +
      "ud.TruckMediaProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.goldingmedia.goldingcloud.PayMetaProtos.getDescriptor(),
          com.goldingmedia.goldingcloud.PlayerMetaProtos.getDescriptor(),
          com.goldingmedia.goldingcloud.MediaMetaProtos.getDescriptor(),
        }, assigner);
    internal_static_goldingcloud_CTruckMediaNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_goldingcloud_CTruckMediaNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_goldingcloud_CTruckMediaNode_descriptor,
        new java.lang.String[] { "CategoryId", "CategorySubId", "MediaInfo", "PlayInfo", "PayInfo", });
    com.goldingmedia.goldingcloud.PayMetaProtos.getDescriptor();
    com.goldingmedia.goldingcloud.PlayerMetaProtos.getDescriptor();
    com.goldingmedia.goldingcloud.MediaMetaProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
