// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpgradeService.proto

package com.goldingmedia.goldingcloud;

public final class UpgradeServiceProtos {
  private UpgradeServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CUpgradeMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:goldingcloud.CUpgradeMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uri = 1;</code>
     */
    java.lang.String getUri();
    /**
     * <code>string uri = 1;</code>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <code>string md5 = 2;</code>
     */
    java.lang.String getMd5();
    /**
     * <code>string md5 = 2;</code>
     */
    com.google.protobuf.ByteString
        getMd5Bytes();

    /**
     * <code>string fileName = 3;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 3;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>string version = 4;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 4;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>string timeStamp = 5;</code>
     */
    java.lang.String getTimeStamp();
    /**
     * <code>string timeStamp = 5;</code>
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <code>.goldingcloud.CUpgradeMeta.Upgrade_Object upobject = 6;</code>
     */
    int getUpobjectValue();
    /**
     * <code>.goldingcloud.CUpgradeMeta.Upgrade_Object upobject = 6;</code>
     */
    com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object getUpobject();

    /**
     * <pre>
     * 1:4G network, 2:SD-CARD, 3:USB, 4:WIFI
     * </pre>
     *
     * <code>int32 upmode = 7;</code>
     */
    int getUpmode();

    /**
     * <pre>
     * 1:master,2:terminal,3:server
     * </pre>
     *
     * <code>int32 dev_type = 8;</code>
     */
    int getDevType();
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code goldingcloud.CUpgradeMeta}
   */
  public  static final class CUpgradeMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:goldingcloud.CUpgradeMeta)
      CUpgradeMetaOrBuilder {
    // Use CUpgradeMeta.newBuilder() to construct.
    private CUpgradeMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CUpgradeMeta() {
      uri_ = "";
      md5_ = "";
      fileName_ = "";
      version_ = "";
      timeStamp_ = "";
      upobject_ = 0;
      upmode_ = 0;
      devType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CUpgradeMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uri_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              md5_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              timeStamp_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              upobject_ = rawValue;
              break;
            }
            case 56: {

              upmode_ = input.readInt32();
              break;
            }
            case 64: {

              devType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.goldingmedia.goldingcloud.UpgradeServiceProtos.internal_static_goldingcloud_CUpgradeMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.goldingmedia.goldingcloud.UpgradeServiceProtos.internal_static_goldingcloud_CUpgradeMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.class, com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Builder.class);
    }

    /**
     * Protobuf enum {@code goldingcloud.CUpgradeMeta.Upgrade_Object}
     */
    public enum Upgrade_Object
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RESERVED = 0;</code>
       */
      RESERVED(0),
      /**
       * <code>UBOOT = 1;</code>
       */
      UBOOT(1),
      /**
       * <code>KERNEL = 2;</code>
       */
      KERNEL(2),
      /**
       * <code>DEVICEDTB = 3;</code>
       */
      DEVICEDTB(3),
      /**
       * <code>ROOTFS = 4;</code>
       */
      ROOTFS(4),
      /**
       * <code>SHARELIB = 5;</code>
       */
      SHARELIB(5),
      /**
       * <code>APPEXE = 6;</code>
       */
      APPEXE(6),
      /**
       * <code>ANDROIDIMG = 7;</code>
       */
      ANDROIDIMG(7),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>RESERVED = 0;</code>
       */
      public static final int RESERVED_VALUE = 0;
      /**
       * <code>UBOOT = 1;</code>
       */
      public static final int UBOOT_VALUE = 1;
      /**
       * <code>KERNEL = 2;</code>
       */
      public static final int KERNEL_VALUE = 2;
      /**
       * <code>DEVICEDTB = 3;</code>
       */
      public static final int DEVICEDTB_VALUE = 3;
      /**
       * <code>ROOTFS = 4;</code>
       */
      public static final int ROOTFS_VALUE = 4;
      /**
       * <code>SHARELIB = 5;</code>
       */
      public static final int SHARELIB_VALUE = 5;
      /**
       * <code>APPEXE = 6;</code>
       */
      public static final int APPEXE_VALUE = 6;
      /**
       * <code>ANDROIDIMG = 7;</code>
       */
      public static final int ANDROIDIMG_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Upgrade_Object valueOf(int value) {
        return forNumber(value);
      }

      public static Upgrade_Object forNumber(int value) {
        switch (value) {
          case 0: return RESERVED;
          case 1: return UBOOT;
          case 2: return KERNEL;
          case 3: return DEVICEDTB;
          case 4: return ROOTFS;
          case 5: return SHARELIB;
          case 6: return APPEXE;
          case 7: return ANDROIDIMG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Upgrade_Object>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Upgrade_Object> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Upgrade_Object>() {
              public Upgrade_Object findValueByNumber(int number) {
                return Upgrade_Object.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.getDescriptor().getEnumTypes().get(0);
      }

      private static final Upgrade_Object[] VALUES = values();

      public static Upgrade_Object valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Upgrade_Object(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:goldingcloud.CUpgradeMeta.Upgrade_Object)
    }

    public static final int URI_FIELD_NUMBER = 1;
    private volatile java.lang.Object uri_;
    /**
     * <code>string uri = 1;</code>
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <code>string uri = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MD5_FIELD_NUMBER = 2;
    private volatile java.lang.Object md5_;
    /**
     * <code>string md5 = 2;</code>
     */
    public java.lang.String getMd5() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        md5_ = s;
        return s;
      }
    }
    /**
     * <code>string md5 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMd5Bytes() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        md5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILENAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 3;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 4;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private volatile java.lang.Object timeStamp_;
    /**
     * <code>string timeStamp = 5;</code>
     */
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeStamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timeStamp = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPOBJECT_FIELD_NUMBER = 6;
    private int upobject_;
    /**
     * <code>.goldingcloud.CUpgradeMeta.Upgrade_Object upobject = 6;</code>
     */
    public int getUpobjectValue() {
      return upobject_;
    }
    /**
     * <code>.goldingcloud.CUpgradeMeta.Upgrade_Object upobject = 6;</code>
     */
    public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object getUpobject() {
      com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object result = com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object.valueOf(upobject_);
      return result == null ? com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object.UNRECOGNIZED : result;
    }

    public static final int UPMODE_FIELD_NUMBER = 7;
    private int upmode_;
    /**
     * <pre>
     * 1:4G network, 2:SD-CARD, 3:USB, 4:WIFI
     * </pre>
     *
     * <code>int32 upmode = 7;</code>
     */
    public int getUpmode() {
      return upmode_;
    }

    public static final int DEV_TYPE_FIELD_NUMBER = 8;
    private int devType_;
    /**
     * <pre>
     * 1:master,2:terminal,3:server
     * </pre>
     *
     * <code>int32 dev_type = 8;</code>
     */
    public int getDevType() {
      return devType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uri_);
      }
      if (!getMd5Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, md5_);
      }
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fileName_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, version_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, timeStamp_);
      }
      if (upobject_ != com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object.RESERVED.getNumber()) {
        output.writeEnum(6, upobject_);
      }
      if (upmode_ != 0) {
        output.writeInt32(7, upmode_);
      }
      if (devType_ != 0) {
        output.writeInt32(8, devType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uri_);
      }
      if (!getMd5Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, md5_);
      }
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fileName_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, version_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, timeStamp_);
      }
      if (upobject_ != com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object.RESERVED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, upobject_);
      }
      if (upmode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, upmode_);
      }
      if (devType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, devType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta)) {
        return super.equals(obj);
      }
      com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta other = (com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta) obj;

      boolean result = true;
      result = result && getUri()
          .equals(other.getUri());
      result = result && getMd5()
          .equals(other.getMd5());
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && getTimeStamp()
          .equals(other.getTimeStamp());
      result = result && upobject_ == other.upobject_;
      result = result && (getUpmode()
          == other.getUpmode());
      result = result && (getDevType()
          == other.getDevType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      hash = (37 * hash) + MD5_FIELD_NUMBER;
      hash = (53 * hash) + getMd5().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
      hash = (37 * hash) + UPOBJECT_FIELD_NUMBER;
      hash = (53 * hash) + upobject_;
      hash = (37 * hash) + UPMODE_FIELD_NUMBER;
      hash = (53 * hash) + getUpmode();
      hash = (37 * hash) + DEV_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDevType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code goldingcloud.CUpgradeMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:goldingcloud.CUpgradeMeta)
        com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.goldingmedia.goldingcloud.UpgradeServiceProtos.internal_static_goldingcloud_CUpgradeMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.goldingmedia.goldingcloud.UpgradeServiceProtos.internal_static_goldingcloud_CUpgradeMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.class, com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Builder.class);
      }

      // Construct using com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uri_ = "";

        md5_ = "";

        fileName_ = "";

        version_ = "";

        timeStamp_ = "";

        upobject_ = 0;

        upmode_ = 0;

        devType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.goldingmedia.goldingcloud.UpgradeServiceProtos.internal_static_goldingcloud_CUpgradeMeta_descriptor;
      }

      public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta getDefaultInstanceForType() {
        return com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.getDefaultInstance();
      }

      public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta build() {
        com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta buildPartial() {
        com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta result = new com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta(this);
        result.uri_ = uri_;
        result.md5_ = md5_;
        result.fileName_ = fileName_;
        result.version_ = version_;
        result.timeStamp_ = timeStamp_;
        result.upobject_ = upobject_;
        result.upmode_ = upmode_;
        result.devType_ = devType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta) {
          return mergeFrom((com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta other) {
        if (other == com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.getDefaultInstance()) return this;
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          onChanged();
        }
        if (!other.getMd5().isEmpty()) {
          md5_ = other.md5_;
          onChanged();
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.getTimeStamp().isEmpty()) {
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (other.upobject_ != 0) {
          setUpobjectValue(other.getUpobjectValue());
        }
        if (other.getUpmode() != 0) {
          setUpmode(other.getUpmode());
        }
        if (other.getDevType() != 0) {
          setDevType(other.getDevType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uri_ = "";
      /**
       * <code>string uri = 1;</code>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uri = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uri = 1;</code>
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 1;</code>
       */
      public Builder clearUri() {
        
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 1;</code>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object md5_ = "";
      /**
       * <code>string md5 = 2;</code>
       */
      public java.lang.String getMd5() {
        java.lang.Object ref = md5_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          md5_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string md5 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMd5Bytes() {
        java.lang.Object ref = md5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          md5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string md5 = 2;</code>
       */
      public Builder setMd5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        md5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string md5 = 2;</code>
       */
      public Builder clearMd5() {
        
        md5_ = getDefaultInstance().getMd5();
        onChanged();
        return this;
      }
      /**
       * <code>string md5 = 2;</code>
       */
      public Builder setMd5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        md5_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 3;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 3;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 3;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 3;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 4;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 4;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 4;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 4;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 4;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timeStamp_ = "";
      /**
       * <code>string timeStamp = 5;</code>
       */
      public java.lang.String getTimeStamp() {
        java.lang.Object ref = timeStamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeStamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timeStamp = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        java.lang.Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timeStamp = 5;</code>
       */
      public Builder setTimeStamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timeStamp = 5;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <code>string timeStamp = 5;</code>
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private int upobject_ = 0;
      /**
       * <code>.goldingcloud.CUpgradeMeta.Upgrade_Object upobject = 6;</code>
       */
      public int getUpobjectValue() {
        return upobject_;
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta.Upgrade_Object upobject = 6;</code>
       */
      public Builder setUpobjectValue(int value) {
        upobject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta.Upgrade_Object upobject = 6;</code>
       */
      public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object getUpobject() {
        com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object result = com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object.valueOf(upobject_);
        return result == null ? com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object.UNRECOGNIZED : result;
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta.Upgrade_Object upobject = 6;</code>
       */
      public Builder setUpobject(com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Upgrade_Object value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        upobject_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta.Upgrade_Object upobject = 6;</code>
       */
      public Builder clearUpobject() {
        
        upobject_ = 0;
        onChanged();
        return this;
      }

      private int upmode_ ;
      /**
       * <pre>
       * 1:4G network, 2:SD-CARD, 3:USB, 4:WIFI
       * </pre>
       *
       * <code>int32 upmode = 7;</code>
       */
      public int getUpmode() {
        return upmode_;
      }
      /**
       * <pre>
       * 1:4G network, 2:SD-CARD, 3:USB, 4:WIFI
       * </pre>
       *
       * <code>int32 upmode = 7;</code>
       */
      public Builder setUpmode(int value) {
        
        upmode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1:4G network, 2:SD-CARD, 3:USB, 4:WIFI
       * </pre>
       *
       * <code>int32 upmode = 7;</code>
       */
      public Builder clearUpmode() {
        
        upmode_ = 0;
        onChanged();
        return this;
      }

      private int devType_ ;
      /**
       * <pre>
       * 1:master,2:terminal,3:server
       * </pre>
       *
       * <code>int32 dev_type = 8;</code>
       */
      public int getDevType() {
        return devType_;
      }
      /**
       * <pre>
       * 1:master,2:terminal,3:server
       * </pre>
       *
       * <code>int32 dev_type = 8;</code>
       */
      public Builder setDevType(int value) {
        
        devType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1:master,2:terminal,3:server
       * </pre>
       *
       * <code>int32 dev_type = 8;</code>
       */
      public Builder clearDevType() {
        
        devType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:goldingcloud.CUpgradeMeta)
    }

    // @@protoc_insertion_point(class_scope:goldingcloud.CUpgradeMeta)
    private static final com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta();
    }

    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CUpgradeMeta>
        PARSER = new com.google.protobuf.AbstractParser<CUpgradeMeta>() {
      public CUpgradeMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CUpgradeMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CUpgradeMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CUpgradeMeta> getParserForType() {
      return PARSER;
    }

    public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CUpgradeServiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:goldingcloud.CUpgradeService)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user = 1;</code>
     */
    java.lang.String getUser();
    /**
     * <code>string user = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    /**
     * <code>string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>int32 port = 3;</code>
     */
    int getPort();

    /**
     * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
     */
    boolean hasUpgradeMeta();
    /**
     * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
     */
    com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta getUpgradeMeta();
    /**
     * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
     */
    com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMetaOrBuilder getUpgradeMetaOrBuilder();
  }
  /**
   * Protobuf type {@code goldingcloud.CUpgradeService}
   */
  public  static final class CUpgradeService extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:goldingcloud.CUpgradeService)
      CUpgradeServiceOrBuilder {
    // Use CUpgradeService.newBuilder() to construct.
    private CUpgradeService(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CUpgradeService() {
      user_ = "";
      password_ = "";
      port_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CUpgradeService(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              user_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 24: {

              port_ = input.readInt32();
              break;
            }
            case 34: {
              com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Builder subBuilder = null;
              if (upgradeMeta_ != null) {
                subBuilder = upgradeMeta_.toBuilder();
              }
              upgradeMeta_ = input.readMessage(com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(upgradeMeta_);
                upgradeMeta_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.goldingmedia.goldingcloud.UpgradeServiceProtos.internal_static_goldingcloud_CUpgradeService_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.goldingmedia.goldingcloud.UpgradeServiceProtos.internal_static_goldingcloud_CUpgradeService_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService.class, com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private volatile java.lang.Object user_;
    /**
     * <code>string user = 1;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      }
    }
    /**
     * <code>string user = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>int32 port = 3;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int UPGRADE_META_FIELD_NUMBER = 4;
    private com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta upgradeMeta_;
    /**
     * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
     */
    public boolean hasUpgradeMeta() {
      return upgradeMeta_ != null;
    }
    /**
     * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
     */
    public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta getUpgradeMeta() {
      return upgradeMeta_ == null ? com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.getDefaultInstance() : upgradeMeta_;
    }
    /**
     * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
     */
    public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMetaOrBuilder getUpgradeMetaOrBuilder() {
      return getUpgradeMeta();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, user_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      if (port_ != 0) {
        output.writeInt32(3, port_);
      }
      if (upgradeMeta_ != null) {
        output.writeMessage(4, getUpgradeMeta());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, user_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      if (upgradeMeta_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getUpgradeMeta());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService)) {
        return super.equals(obj);
      }
      com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService other = (com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService) obj;

      boolean result = true;
      result = result && getUser()
          .equals(other.getUser());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && (getPort()
          == other.getPort());
      result = result && (hasUpgradeMeta() == other.hasUpgradeMeta());
      if (hasUpgradeMeta()) {
        result = result && getUpgradeMeta()
            .equals(other.getUpgradeMeta());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      if (hasUpgradeMeta()) {
        hash = (37 * hash) + UPGRADE_META_FIELD_NUMBER;
        hash = (53 * hash) + getUpgradeMeta().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code goldingcloud.CUpgradeService}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:goldingcloud.CUpgradeService)
        com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeServiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.goldingmedia.goldingcloud.UpgradeServiceProtos.internal_static_goldingcloud_CUpgradeService_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.goldingmedia.goldingcloud.UpgradeServiceProtos.internal_static_goldingcloud_CUpgradeService_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService.class, com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService.Builder.class);
      }

      // Construct using com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        user_ = "";

        password_ = "";

        port_ = 0;

        if (upgradeMetaBuilder_ == null) {
          upgradeMeta_ = null;
        } else {
          upgradeMeta_ = null;
          upgradeMetaBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.goldingmedia.goldingcloud.UpgradeServiceProtos.internal_static_goldingcloud_CUpgradeService_descriptor;
      }

      public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService getDefaultInstanceForType() {
        return com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService.getDefaultInstance();
      }

      public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService build() {
        com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService buildPartial() {
        com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService result = new com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService(this);
        result.user_ = user_;
        result.password_ = password_;
        result.port_ = port_;
        if (upgradeMetaBuilder_ == null) {
          result.upgradeMeta_ = upgradeMeta_;
        } else {
          result.upgradeMeta_ = upgradeMetaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService) {
          return mergeFrom((com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService other) {
        if (other == com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService.getDefaultInstance()) return this;
        if (!other.getUser().isEmpty()) {
          user_ = other.user_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.hasUpgradeMeta()) {
          mergeUpgradeMeta(other.getUpgradeMeta());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object user_ = "";
      /**
       * <code>string user = 1;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user = 1;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user = 1;</code>
       */
      public Builder clearUser() {
        
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>string user = 1;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        user_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 3;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta upgradeMeta_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta, com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Builder, com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMetaOrBuilder> upgradeMetaBuilder_;
      /**
       * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
       */
      public boolean hasUpgradeMeta() {
        return upgradeMetaBuilder_ != null || upgradeMeta_ != null;
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
       */
      public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta getUpgradeMeta() {
        if (upgradeMetaBuilder_ == null) {
          return upgradeMeta_ == null ? com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.getDefaultInstance() : upgradeMeta_;
        } else {
          return upgradeMetaBuilder_.getMessage();
        }
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
       */
      public Builder setUpgradeMeta(com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta value) {
        if (upgradeMetaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          upgradeMeta_ = value;
          onChanged();
        } else {
          upgradeMetaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
       */
      public Builder setUpgradeMeta(
          com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Builder builderForValue) {
        if (upgradeMetaBuilder_ == null) {
          upgradeMeta_ = builderForValue.build();
          onChanged();
        } else {
          upgradeMetaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
       */
      public Builder mergeUpgradeMeta(com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta value) {
        if (upgradeMetaBuilder_ == null) {
          if (upgradeMeta_ != null) {
            upgradeMeta_ =
              com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.newBuilder(upgradeMeta_).mergeFrom(value).buildPartial();
          } else {
            upgradeMeta_ = value;
          }
          onChanged();
        } else {
          upgradeMetaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
       */
      public Builder clearUpgradeMeta() {
        if (upgradeMetaBuilder_ == null) {
          upgradeMeta_ = null;
          onChanged();
        } else {
          upgradeMeta_ = null;
          upgradeMetaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
       */
      public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Builder getUpgradeMetaBuilder() {
        
        onChanged();
        return getUpgradeMetaFieldBuilder().getBuilder();
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
       */
      public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMetaOrBuilder getUpgradeMetaOrBuilder() {
        if (upgradeMetaBuilder_ != null) {
          return upgradeMetaBuilder_.getMessageOrBuilder();
        } else {
          return upgradeMeta_ == null ?
              com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.getDefaultInstance() : upgradeMeta_;
        }
      }
      /**
       * <code>.goldingcloud.CUpgradeMeta upgrade_meta = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta, com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Builder, com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMetaOrBuilder> 
          getUpgradeMetaFieldBuilder() {
        if (upgradeMetaBuilder_ == null) {
          upgradeMetaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta, com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMeta.Builder, com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeMetaOrBuilder>(
                  getUpgradeMeta(),
                  getParentForChildren(),
                  isClean());
          upgradeMeta_ = null;
        }
        return upgradeMetaBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:goldingcloud.CUpgradeService)
    }

    // @@protoc_insertion_point(class_scope:goldingcloud.CUpgradeService)
    private static final com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService();
    }

    public static com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CUpgradeService>
        PARSER = new com.google.protobuf.AbstractParser<CUpgradeService>() {
      public CUpgradeService parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CUpgradeService(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CUpgradeService> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CUpgradeService> getParserForType() {
      return PARSER;
    }

    public com.goldingmedia.goldingcloud.UpgradeServiceProtos.CUpgradeService getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_goldingcloud_CUpgradeMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_goldingcloud_CUpgradeMeta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_goldingcloud_CUpgradeService_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_goldingcloud_CUpgradeService_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024UpgradeService.proto\022\014goldingcloud\"\271\002\n" +
      "\014CUpgradeMeta\022\013\n\003uri\030\001 \001(\t\022\013\n\003md5\030\002 \001(\t\022" +
      "\020\n\010fileName\030\003 \001(\t\022\017\n\007version\030\004 \001(\t\022\021\n\tti" +
      "meStamp\030\005 \001(\t\022;\n\010upobject\030\006 \001(\0162).goldin" +
      "gcloud.CUpgradeMeta.Upgrade_Object\022\016\n\006up" +
      "mode\030\007 \001(\005\022\020\n\010dev_type\030\010 \001(\005\"z\n\016Upgrade_" +
      "Object\022\014\n\010RESERVED\020\000\022\t\n\005UBOOT\020\001\022\n\n\006KERNE" +
      "L\020\002\022\r\n\tDEVICEDTB\020\003\022\n\n\006ROOTFS\020\004\022\014\n\010SHAREL" +
      "IB\020\005\022\n\n\006APPEXE\020\006\022\016\n\nANDROIDIMG\020\007\"q\n\017CUpg" +
      "radeService\022\014\n\004user\030\001 \001(\t\022\020\n\010password\030\002 ",
      "\001(\t\022\014\n\004port\030\003 \001(\005\0220\n\014upgrade_meta\030\004 \001(\0132" +
      "\032.goldingcloud.CUpgradeMetaBj\n\035com.goldi" +
      "ngmedia.goldingcloudB\024UpgradeServiceProt" +
      "os\252\0022com.goldingmedia.goldingcloud.Upgra" +
      "deServiceProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_goldingcloud_CUpgradeMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_goldingcloud_CUpgradeMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_goldingcloud_CUpgradeMeta_descriptor,
        new java.lang.String[] { "Uri", "Md5", "FileName", "Version", "TimeStamp", "Upobject", "Upmode", "DevType", });
    internal_static_goldingcloud_CUpgradeService_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_goldingcloud_CUpgradeService_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_goldingcloud_CUpgradeService_descriptor,
        new java.lang.String[] { "User", "Password", "Port", "UpgradeMeta", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
