// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VeriFace.proto

package com.goldingmedia.goldingcloud;

public final class VeriFaceProtos {
  private VeriFaceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CVeriFaceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:goldingcloud.CVeriFace)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1:master,2:terminal,3:server
     * </pre>
     *
     * <code>int32 device_type = 1;</code>
     */
    int getDeviceType();

    /**
     * <pre>
     *CPU ID
     * </pre>
     *
     * <code>string device_id = 2;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <pre>
     *CPU ID
     * </pre>
     *
     * <code>string device_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <pre>
     *passenger seat number
     * </pre>
     *
     * <code>int32 passenger_seat_id = 3;</code>
     */
    int getPassengerSeatId();

    /**
     * <pre>
     *man/woman
     * </pre>
     *
     * <code>bool passenger_sex = 4;</code>
     */
    boolean getPassengerSex();

    /**
     * <pre>
     *value range
     * </pre>
     *
     * <code>int32 passenger_age = 5;</code>
     */
    int getPassengerAge();

    /**
     * <pre>
     *favorite
     * </pre>
     *
     * <code>int32 passenger_favorite = 6;</code>
     */
    int getPassengerFavorite();
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code goldingcloud.CVeriFace}
   */
  public  static final class CVeriFace extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:goldingcloud.CVeriFace)
      CVeriFaceOrBuilder {
    // Use CVeriFace.newBuilder() to construct.
    private CVeriFace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CVeriFace() {
      deviceType_ = 0;
      deviceId_ = "";
      passengerSeatId_ = 0;
      passengerSex_ = false;
      passengerAge_ = 0;
      passengerFavorite_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CVeriFace(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              deviceType_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 24: {

              passengerSeatId_ = input.readInt32();
              break;
            }
            case 32: {

              passengerSex_ = input.readBool();
              break;
            }
            case 40: {

              passengerAge_ = input.readInt32();
              break;
            }
            case 48: {

              passengerFavorite_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.goldingmedia.goldingcloud.VeriFaceProtos.internal_static_goldingcloud_CVeriFace_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.goldingmedia.goldingcloud.VeriFaceProtos.internal_static_goldingcloud_CVeriFace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace.class, com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace.Builder.class);
    }

    public static final int DEVICE_TYPE_FIELD_NUMBER = 1;
    private int deviceType_;
    /**
     * <pre>
     *1:master,2:terminal,3:server
     * </pre>
     *
     * <code>int32 device_type = 1;</code>
     */
    public int getDeviceType() {
      return deviceType_;
    }

    public static final int DEVICE_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceId_;
    /**
     * <pre>
     *CPU ID
     * </pre>
     *
     * <code>string device_id = 2;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *CPU ID
     * </pre>
     *
     * <code>string device_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSENGER_SEAT_ID_FIELD_NUMBER = 3;
    private int passengerSeatId_;
    /**
     * <pre>
     *passenger seat number
     * </pre>
     *
     * <code>int32 passenger_seat_id = 3;</code>
     */
    public int getPassengerSeatId() {
      return passengerSeatId_;
    }

    public static final int PASSENGER_SEX_FIELD_NUMBER = 4;
    private boolean passengerSex_;
    /**
     * <pre>
     *man/woman
     * </pre>
     *
     * <code>bool passenger_sex = 4;</code>
     */
    public boolean getPassengerSex() {
      return passengerSex_;
    }

    public static final int PASSENGER_AGE_FIELD_NUMBER = 5;
    private int passengerAge_;
    /**
     * <pre>
     *value range
     * </pre>
     *
     * <code>int32 passenger_age = 5;</code>
     */
    public int getPassengerAge() {
      return passengerAge_;
    }

    public static final int PASSENGER_FAVORITE_FIELD_NUMBER = 6;
    private int passengerFavorite_;
    /**
     * <pre>
     *favorite
     * </pre>
     *
     * <code>int32 passenger_favorite = 6;</code>
     */
    public int getPassengerFavorite() {
      return passengerFavorite_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (deviceType_ != 0) {
        output.writeInt32(1, deviceType_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
      }
      if (passengerSeatId_ != 0) {
        output.writeInt32(3, passengerSeatId_);
      }
      if (passengerSex_ != false) {
        output.writeBool(4, passengerSex_);
      }
      if (passengerAge_ != 0) {
        output.writeInt32(5, passengerAge_);
      }
      if (passengerFavorite_ != 0) {
        output.writeInt32(6, passengerFavorite_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (deviceType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deviceType_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
      }
      if (passengerSeatId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, passengerSeatId_);
      }
      if (passengerSex_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, passengerSex_);
      }
      if (passengerAge_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, passengerAge_);
      }
      if (passengerFavorite_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, passengerFavorite_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace)) {
        return super.equals(obj);
      }
      com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace other = (com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace) obj;

      boolean result = true;
      result = result && (getDeviceType()
          == other.getDeviceType());
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && (getPassengerSeatId()
          == other.getPassengerSeatId());
      result = result && (getPassengerSex()
          == other.getPassengerSex());
      result = result && (getPassengerAge()
          == other.getPassengerAge());
      result = result && (getPassengerFavorite()
          == other.getPassengerFavorite());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceType();
      hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + PASSENGER_SEAT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPassengerSeatId();
      hash = (37 * hash) + PASSENGER_SEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPassengerSex());
      hash = (37 * hash) + PASSENGER_AGE_FIELD_NUMBER;
      hash = (53 * hash) + getPassengerAge();
      hash = (37 * hash) + PASSENGER_FAVORITE_FIELD_NUMBER;
      hash = (53 * hash) + getPassengerFavorite();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code goldingcloud.CVeriFace}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:goldingcloud.CVeriFace)
        com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFaceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.goldingmedia.goldingcloud.VeriFaceProtos.internal_static_goldingcloud_CVeriFace_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.goldingmedia.goldingcloud.VeriFaceProtos.internal_static_goldingcloud_CVeriFace_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace.class, com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace.Builder.class);
      }

      // Construct using com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deviceType_ = 0;

        deviceId_ = "";

        passengerSeatId_ = 0;

        passengerSex_ = false;

        passengerAge_ = 0;

        passengerFavorite_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.goldingmedia.goldingcloud.VeriFaceProtos.internal_static_goldingcloud_CVeriFace_descriptor;
      }

      public com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace getDefaultInstanceForType() {
        return com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace.getDefaultInstance();
      }

      public com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace build() {
        com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace buildPartial() {
        com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace result = new com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace(this);
        result.deviceType_ = deviceType_;
        result.deviceId_ = deviceId_;
        result.passengerSeatId_ = passengerSeatId_;
        result.passengerSex_ = passengerSex_;
        result.passengerAge_ = passengerAge_;
        result.passengerFavorite_ = passengerFavorite_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace) {
          return mergeFrom((com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace other) {
        if (other == com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace.getDefaultInstance()) return this;
        if (other.getDeviceType() != 0) {
          setDeviceType(other.getDeviceType());
        }
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.getPassengerSeatId() != 0) {
          setPassengerSeatId(other.getPassengerSeatId());
        }
        if (other.getPassengerSex() != false) {
          setPassengerSex(other.getPassengerSex());
        }
        if (other.getPassengerAge() != 0) {
          setPassengerAge(other.getPassengerAge());
        }
        if (other.getPassengerFavorite() != 0) {
          setPassengerFavorite(other.getPassengerFavorite());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int deviceType_ ;
      /**
       * <pre>
       *1:master,2:terminal,3:server
       * </pre>
       *
       * <code>int32 device_type = 1;</code>
       */
      public int getDeviceType() {
        return deviceType_;
      }
      /**
       * <pre>
       *1:master,2:terminal,3:server
       * </pre>
       *
       * <code>int32 device_type = 1;</code>
       */
      public Builder setDeviceType(int value) {
        
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1:master,2:terminal,3:server
       * </pre>
       *
       * <code>int32 device_type = 1;</code>
       */
      public Builder clearDeviceType() {
        
        deviceType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <pre>
       *CPU ID
       * </pre>
       *
       * <code>string device_id = 2;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *CPU ID
       * </pre>
       *
       * <code>string device_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *CPU ID
       * </pre>
       *
       * <code>string device_id = 2;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *CPU ID
       * </pre>
       *
       * <code>string device_id = 2;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *CPU ID
       * </pre>
       *
       * <code>string device_id = 2;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private int passengerSeatId_ ;
      /**
       * <pre>
       *passenger seat number
       * </pre>
       *
       * <code>int32 passenger_seat_id = 3;</code>
       */
      public int getPassengerSeatId() {
        return passengerSeatId_;
      }
      /**
       * <pre>
       *passenger seat number
       * </pre>
       *
       * <code>int32 passenger_seat_id = 3;</code>
       */
      public Builder setPassengerSeatId(int value) {
        
        passengerSeatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *passenger seat number
       * </pre>
       *
       * <code>int32 passenger_seat_id = 3;</code>
       */
      public Builder clearPassengerSeatId() {
        
        passengerSeatId_ = 0;
        onChanged();
        return this;
      }

      private boolean passengerSex_ ;
      /**
       * <pre>
       *man/woman
       * </pre>
       *
       * <code>bool passenger_sex = 4;</code>
       */
      public boolean getPassengerSex() {
        return passengerSex_;
      }
      /**
       * <pre>
       *man/woman
       * </pre>
       *
       * <code>bool passenger_sex = 4;</code>
       */
      public Builder setPassengerSex(boolean value) {
        
        passengerSex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *man/woman
       * </pre>
       *
       * <code>bool passenger_sex = 4;</code>
       */
      public Builder clearPassengerSex() {
        
        passengerSex_ = false;
        onChanged();
        return this;
      }

      private int passengerAge_ ;
      /**
       * <pre>
       *value range
       * </pre>
       *
       * <code>int32 passenger_age = 5;</code>
       */
      public int getPassengerAge() {
        return passengerAge_;
      }
      /**
       * <pre>
       *value range
       * </pre>
       *
       * <code>int32 passenger_age = 5;</code>
       */
      public Builder setPassengerAge(int value) {
        
        passengerAge_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *value range
       * </pre>
       *
       * <code>int32 passenger_age = 5;</code>
       */
      public Builder clearPassengerAge() {
        
        passengerAge_ = 0;
        onChanged();
        return this;
      }

      private int passengerFavorite_ ;
      /**
       * <pre>
       *favorite
       * </pre>
       *
       * <code>int32 passenger_favorite = 6;</code>
       */
      public int getPassengerFavorite() {
        return passengerFavorite_;
      }
      /**
       * <pre>
       *favorite
       * </pre>
       *
       * <code>int32 passenger_favorite = 6;</code>
       */
      public Builder setPassengerFavorite(int value) {
        
        passengerFavorite_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *favorite
       * </pre>
       *
       * <code>int32 passenger_favorite = 6;</code>
       */
      public Builder clearPassengerFavorite() {
        
        passengerFavorite_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:goldingcloud.CVeriFace)
    }

    // @@protoc_insertion_point(class_scope:goldingcloud.CVeriFace)
    private static final com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace();
    }

    public static com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CVeriFace>
        PARSER = new com.google.protobuf.AbstractParser<CVeriFace>() {
      public CVeriFace parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CVeriFace(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CVeriFace> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CVeriFace> getParserForType() {
      return PARSER;
    }

    public com.goldingmedia.goldingcloud.VeriFaceProtos.CVeriFace getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_goldingcloud_CVeriFace_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_goldingcloud_CVeriFace_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016VeriFace.proto\022\014goldingcloud\"\230\001\n\tCVeri" +
      "Face\022\023\n\013device_type\030\001 \001(\005\022\021\n\tdevice_id\030\002" +
      " \001(\t\022\031\n\021passenger_seat_id\030\003 \001(\005\022\025\n\rpasse" +
      "nger_sex\030\004 \001(\010\022\025\n\rpassenger_age\030\005 \001(\005\022\032\n" +
      "\022passenger_favorite\030\006 \001(\005B^\n\035com.golding" +
      "media.goldingcloudB\016VeriFaceProtos\252\002,com" +
      ".goldingmedia.goldingcloud.VeriFaceProto" +
      "sb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_goldingcloud_CVeriFace_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_goldingcloud_CVeriFace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_goldingcloud_CVeriFace_descriptor,
        new java.lang.String[] { "DeviceType", "DeviceId", "PassengerSeatId", "PassengerSex", "PassengerAge", "PassengerFavorite", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
